if( GetLocale() ~= "esES" ) then return end
local L = {}
L["--"] = "--"
L["---"] = "---"
L["<1 minute old"] = "< hace menos de un minuto"
L["Active"] = "Activo"
L["Add"] = "Añadir"
L["Add an user manually"] = "Añadir un usuario manualmente"
L["Addon communication"] = "Comunicacion de addon"
L["Adds summary information to the main inspection window."] = "Añade informacion del sumario a la ventana principal de inspeccion"
L["Adds tooltips when mousing over inspected items indicating the items type, and if the gems and enchants pass."] = "Añade pistas cuando se pasa el raton sobre objetos inspeccionados indicando el tipo de objeto y si las gemas y encantamientos son correctos"
L["Affliction"] = "Afliccion"
L["After completing a dungeon through the Looking For Dungeon system, automatically popup the /rate frame so you can set notes and rating on your group members."] = "Despues de completar una mazmorra a traves del Sistema de Busqueda de Mazmorras, sacar automaticamente el cuadro /rate de forma que puedas poner notas y calificar los miembros de tu grupo"
L["Alerts you in chat when you receive new notes or gear information from somebody."] = "Te avisa en chat cuando recibes nuevas notas o informacion de equipo de alguien "
L["Alert when grouped with low rated players"] = "Avisar cuando te juntes en grupo con jugadores con baja calificacion"
L["All"] = "Todos"
L["Allow database syncing"] = "Permitir sincronizar base de datos"
L["Allow gear requests"] = "Permitir peticiones de equipo"
L["Allows both you and other people on your trusted list to send and request your database of users."] = "Permite a ti y a otras personas que estan  en la lista de fiables enviarte y pedirte datos de tu base de datos de usuarios"
L["ALT + Left Click - Open report window for group"] = "ALT + Click Izquierdo - Abre la ventana de informes de tu grupo"
L["ALT + Right Click - Open rating window for party"] = "ALT + Click Derecho- abre la ventana de calificacion para grupos."
L["ALT + Right Click - Open rating window for raid"] = "ALT + Click Derecho - Abre ventana de calificacion para banda"
L["Always bad"] = "Siempre Incorrecta"
L["Always process group queue"] = "Procesar siempre la cola de grupo"
L["Announce synced data"] = "Anunciar sincronizacion de datos"
L["Any data from another server will not be saved, this includes notes! If you would like most of the data to be pruned but notes kept intact change basic pruning and leave this on."] = "Cualquier dato de otro servidor no sera salvado, esto incluye las notas!. Si deseas que la mayor parte de los datos sea depurado pero las notas permanezcan intactas cambia el depurado basico y habilitalo"
L["Any data older than the set number will not be synced."] = "Cualquier dato mas antiguo que el numero indicado no sera sincronizado"
L["Arcane"] = "Arcano"
L["Archavon the Stone Watcher"] = "Archavon el vigia de piedra"
L["Archavon, Vault"] = "Archavon, Camara"
L["Are you sure you want to reset ALL user data recorded, including notes?"] = "Estas seguro de que quieres resetear todos los datos de usuario grabados, incluyendo notas?"
L["armor by"] = "armadura por"
L["armor for"] = "amadura para"
L["Arms"] = "Armas"
L["Assassination"] = "Asesinato"
L["Automatically"] = "Automaticamente"
L["Automatically requests main experience (limited at once per an hour) when inspecting."] = "Pedir automaticamente la experiencia del main(limitada a una vez por hora) cuando inspeccionas"
L["Automatically requests notes on your group from other Elitist Group users. Only sends requests once per session, and you have to be in a guild."] = "Pedir notas automaticamente sobre tu grupo de otros usuarios de Elitist Group. Solo envia peticiones una vez por sesion , y tu tienes que pertenecer a una hermandad"
L["Automatically trust all guild members, if you are in a guild."] = "Confia automaticamente en todos los miembros de la hermandad, si estas en una hermandad."
L["Automatically trusts all players on your friends list."] = "Confia automaticante en todos los jugadores de tu lista de amigos"
L["Auto request main experience"] = "Pedir experiencia del main automaticamente"
L["Auto request notes"] = "Pedir notas automaticamente"
L["Average"] = "Medio"
L["[average ilvl]"] = "[Nivel medio de equipo]"
L["average item level below %d"] = "Nivel medio de objeto por debajo de %d"
L["Average item level of the players equipment."] = "Nivel medio de objetos del equipo del jugador"
L["Average rating %.2f of %d, rated %d times."] = "Calificacion media %.2f de %d, calificado %d veces."
L["[bad enchants]"] = "[encantamientos incorrectos]"
L["[bad equipment]"] = "[Equipo incorrecto]"
L["[bad gems]"] = "[Gemas incorrectas]"
L["Balance"] = "Equilibrio"
L["Battleground channel"] = "Canal de Campo de Batalla"
L["Beast Mastery"] = "Maestro de bestias"
L["Blood"] = "Sangre"
L["c%-\"(.-)\""] = "c%-\"(.-)\""
L["Cannot find record of %s in your saved database."] = "No puedo encontrar datos de %s en tu base de datos guardada"
L["Cannot find URL for this player, don't seem to have name, server or region data."] = "No puedo encontrar la URL de este jugador, no parece tener datos de  nombre, servidor o region"
L["Cannot inspect %s yet, you have to wait %.1f seconds before you can inspect again."] = "No puedo inspeccionar a %s aun, tienes que esperar %.1f segundos antes de que puedas inspeccionar de nuevo."
L["Caster (All)"] = "Caster (todos)"
L["Caster (Spirit)"] = "Caster(Espiritu)"
L["|cff%02x%02x00%d|r avg, %d-man (%s)"] = "|cff%02x%02x00%d|r medio %d-persona (%s)"
L["[|cff%02x%02x00%d%%|r] Enchants"] = "[|cff%02x%02x00%d%%|r] Encantamientos"
L["[|cff%02x%02x00%d%%|r] Equipment (%s%d|r)"] = "[|cff%02x%02x00%d%%|r] Equipo (%s%d|r)"
L["[|cff%02x%02x00%d%%|r] Gems"] = "[|cff%02x%02x00%d%%|r] Gemas"
L["[|cff%02x%02x00%d%%|r] [%s%d|r] Equipment"] = "[|cff%02x%02x00%d%%|r] [%s%d|r] Equipo"
L["|cfffed000Item Type:|r %s%s"] = "|cfffed000Tipo de Objeto:|r %s%s"
L["[|cffff20200%|r] Enchants"] = "[|cffff20200%|r] Encantamientos"
L["[|cffff20200%|r] Gems"] = "[|cffff20200%|r] Gemas"
L["|cffff2020%d unspent |4point:points;|r"] = "|cffff2020%d no gastado(s) |4punto:puntos;|r"
L["|cffff2020%d unspent|r (Secondary)"] = "|cffff2020%d no gastado(s)|r (Secundaria)"
L["|cffff2020Warning!|r %s is in your group, you rated them %d"] = "|cffff2020Atencion!|r %s esta en tu grupo. Tu lo calificaste %d"
L["|cffff2020Warning!|r %s is in your group, you rated them %d for: %s"] = "|cffff2020Atencion!|r %s esta en tu grupo. Tu calificaste %d para : %s"
L[ [=[
|cffffffffAND|r
]=] ] = [=[|cffffffffAND|r
]=]
L[ [=[
|cffffffffOR|r
]=] ] = [=[|cffffffffOR|r
]=]
L["|cffffffff%s|r %s, %s role."] = "|cffffffff%s|r %s, %s rol."
L[ [=[|cffffffff%s|r %s, %s role.

The player has not spent %d talent points.]=] ] = [=[|cffffffff%s|r %s, %s rol.

]=]
L[ [=[|cffffffff%s|r %s, %s role.

The player put all of his talent points into one tree.]=] ] = [=[ |cffffffff%s|r %s, %s rol.

 ]=]
L["chance on melee and range"] = "oportunidad a mele y a distancia"
L["chance on melee attack"] = "Oportunidad en ataque a mele"
L["chance on melee or range"] = "oportunidad a mele o a distancia"
L["Channel to report Elitist Group summary to."] = "Canal para incluir el sumario de Elitist Group"
L["Classes"] = "Clases"
L["Click to open and close the database viewer."] = "Pulsa para abrir y cerrar el visor de base de datos"
L["Click to view detailed information."] = "Pulsa para ver informacion detallada"
L["Combat"] = "Combate"
L["Comment"] = "Comentario"
L["Comment..."] = "Comentario.."
L["Completed %s! Type /rate to rate this group."] = "Completado %s!! Escrite /rate para calificar este grupo"
L["Could not calculate average item level, no data found."] = "No se puede calcular el nivel medio de objeto , datos no encontrados"
L[ [=[Current filters are all players who have:

]=] ] = [=[Los filtros actuales son todos los jugadores que tengan:

]=]
L["Custom list"] = "Lista a medida"
L["<= %d"] = "<= %d"
L["> %d%%"] = "> %d%%"
L["%d |4day:days;"] = "%d |4dia:dias;"
L["%d |4day:days; old"] = "%d |4dia:dias; antes"
L["%d |4hour:hours;"] = "%d |4hora:horas;"
L["%d |4hour:hours; old"] = "%d |4hora:horas; antes"
L["%d |4minute:minutes;"] = "%d |4minuto:minutos;"
L["%d |4minute:minutes; old"] = "%d |4minuto:minutos; antes"
L["Database"] = "Base de datos"
L["Data for this player is from a verified source and can be trusted."] = "Los datos de este jugador vienen de un origen verificado y  se puede confiar en ellos."
L[ [=[Data has been pruned to save database space.

Perhaps you want to change prune settings in /eg config?]=] ] = [=[Los datos han sido depurados para ahorrar espacion en la base de datos

Quiza quieres cambiar los controles de depurado en /eg config?]=]
L["Data is loading, please wait."] = "Los datos se estan cargando, por favor espera."
L["%d average rating"] = "%d calificacion media"
L[">= %d%% bad enchants"] = ">= %d%%  encantamientos  incorrectos"
L["> %d%% bad gear"] = "> %d%% equipo incorrecto"
L[">= %d%% bad gems"] = ">= %d%% gemas incorrectas"
L["deal damage"] = "hacer daño"
L["Delete"] = "Borrar"
L["Demonology"] = "Demonologia"
L["Destruction"] = "Destruccion"
L["Discipline"] = "Disciplina"
L[" (%d-man)"] = "%d Persona"
L[ [=[Do not abuse this!

Abuse will result in the feature being removed.]=] ] = [=[No abuses de esto!

Los abusos tendran como resultado que esta funcionalidad sea eliminada]=]
L["Do not require players who are below the given level."] = "No buscar jugadores que estan por debajo del nivel dado."
L["Don't include"] = "No incluir"
L["Don't include enchants"] = "No incluir encantamientos"
L["Don't include gear"] = "No incluir equipo"
L["Don't include gems"] = "No incluir gemas"
L["Don't include item level"] = "No incluir nivel de objetos"
L["%d%% or more bad enchants"] = "%d%% o mas  encantamientos incorrectos"
L["%d%% or more bad equipped items"] = "%d%% o mas objetos equipados  incorrectos"
L["%d%% or more bad gems"] = "%d%% o mas gemas  incorrectas"
L["DPS (All)"] = "DPS(Todos)"
L["DPS (Caster)"] = "DPS (Caster)"
L["DPS, Caster"] = "DPS, Caster"
L["DPS (Melee)"] = "DPS (Mele)"
L["DPS, Melee"] = "DPS, Mele"
L["DPS (Physical)"] = "DPS (Fisico)"
L["DPS (Ranged)"] = "DPS(A distancia)"
L["DPS, Ranged"] = "DPS, a distancia"
L["Dungeons"] = "Mazmorras"
L["%d unspent |4point:points;"] = "%d no gastados |4punto:puntos;"
L[" (%d unused |4socket:sockets;)"] = " (%d sin usar |4ranura:ranuras;)"
L["Edit"] = "Editar"
L["/eg config - Opens the configuration"] = "/eg config - Abre la configuracion"
L["/eg db [name] - Requests either everyones database or [name]s database if specified"] = "/eg db [nombre] - Pide o la base de datos de cualquiera o la base de datos de [nombre]"
L["/eg gear <name> - Requests gear from another Elitist Group user without inspecting"] = "/eg gear <nombre> - Pide el equipo de otro usuario de Elitist Group sin inspeccionar"
L["/eg leader - Opens the specialized group manager/former UI"] = "/eg leader - Abre el gestor de grupo especializado"
L["/eg <name> - When <name> is passed opens up the player viewer for that person, otherwise it opens it on yourself"] = "/eg <nombre> - cuando se le pasa  <nombre> abre el visor para esa persona, de otro modo lo abre para ti mismo"
L["/eg notes [name] - Requests all guild members notes on players, if [name] is passed requests notes FROM [name]"] = "/eg notes [nombre] - Pide notas de todos lo miembros de la guild en jugadores. si añades [nombre] pide las notas DESDE [nombre]"
L["/eg rate - Opens the rating panel for your group"] = "/eg rate -abre el panel de calificacion para tu grupo"
L["/eg report - Opens the reporting UI for sending to chat summaries on your group"] = "/eg report - abre la interfaz de informes para enviar al chat sumarios o resumenes de tu grupo"
L["/eg send <name> - Sends your gear to another Elitist Group user"] = "/eg send <nombre> - envia tu equipo a otro miembro de Elitist Group "
L["/eg summary - Displays the summary page for your party or raid"] = "/eg summary - Muestra la pagina de sumario para tu grupo o banda"
L["Elemental"] = "Elemental"
L["Elitist Group (%s): showing %d players, check out http://elitistarmory.com for more info. Format is, [name] (%s)"] = "Elitist Group (%s): mostrando %d jugadores, revisa  http://elitistarmory.com para mas informacino. el formato es [nombre] (%d)"
L["Emalon the Storm Watcher"] = "Emalon el vigilante de la tormenta"
L["Emalon, Vault"] = "Emalon, Camara"
L["Enable comms"] = "Activar comentarios"
L["Enabled channels"] = "Activar canales"
L["Enchant"] = "Encantamiento"
L["Enchant: |cffff2020[!]|r |cffffffffNone found|r"] = "Encantamiento: |cffff2020[!]|r |cffffffffNo encontrado ninguno|r"
L["Enchant: |cffff2020[!]|r |cffffffff%s|r enchant"] = "Encantamiento: |cffff2020[!]|r |cffffffff%s|r encantamiento"
L["Enchant: |cffffffffCannot enchant|r"] = "Encantamiento: |cffffffffNo puede encantar|r"
L["Enchant: |cffffffffPass|r"] = "Encantamiento: |cffffffffCorrecto|r"
L["Enchants"] = "Encantamientos"
L["Enchants [|cff%02x%02x00%d%%|r]"] = "Encantamientos [|cff%02x%02x00%d%%|r]"
L["Enchants [|cffff20200%|r]"] = "Encantamientos [|cffff20200%|r]"
L["Enchants: |cffffffff%d bad|r"] = "Encantamientos: |cffffffff%d Incorrecto|r"
L["Enchants: |cffffffffPass|r"] = "Encantamientos: |cffffffffCorrecto|r"
L["Enchants: |cffffffffThe player does not have any enchants|r"] = "Encantamientos: |cffffffffEl personaje no tiene ningun encantamiento|r"
L["Enhancement"] = "Mejora"
L["Equipment"] = "Equipo"
L["Equipment: |cffffffff%d bad items found|r"] = "Equipo: |cffffffff%d Objetos incorrectos encontrados|r"
L["Equipment: |cffffffffPass|r"] = "Equipo: |cffffffffCorrecto|r"
L["Experience"] = "Experiencia"
L["Experienced"] = "Experimentado"
L["fear duration"] = "Duracion de Miedo"
L["Feral"] = "Feral"
L["Fire"] = "Fuego"
L["Frost"] = "Escarcha"
L["Fury"] = "Furia"
L["Gear"] = "Equipo"
L["Gear received from %s."] = "Equipo recibido de  %s."
L["Gems"] = "Gemas"
L["Gems [|cff%02x%02x00%d%%|r]"] = "Gemas [|cff%02x%02x00%d%%|r]"
L["Gems [|cffff20200%|r]"] = "Gemas [|cffff20200%|r]"
L["Gems: |cffff2020[!]|r |cffffffff%d bad|r%s"] = "Gemas: |cffff2020[!]|r |cffffffff%d incorrecta(s)|r%s"
L["Gems: |cffffffff%d bad|r"] = "Gemas: |cffffffff%d incorrectas|r"
L["Gems: |cffffffffFailed to find any gems|r"] = "Gemas: |cffffffffNo se puede encontrar ninguna gema|r"
L["Gems: |cffffffffNo sockets|r"] = "Gemas: |cffffffffNo hay ranuras|r"
L["Gems: |cffffffffPass|r"] = "Gems: |cffffffffCorrecto|r"
L["Gems/Enchant"] = "Gemas/Encantamientos"
L["General"] = "General"
L["Great"] = "Grande"
L["guild"] = "hermandad"
L["Guild"] = "Hermandad"
L["Guild channel"] = "Canal de Hermandad"
L["Hard"] = "Dificil"
L["harmful spell"] = "Hechizo dañino"
L["Healer"] = "Sanador"
L["Healer (All)"] = "Sanador (todos)"
L["Healer/DPS"] = "Sanador/DPS"
L["Healing Priest/Druid"] = "Priest Sanador/Druida"
L["Help"] = "Ayuda"
L["helpful spell"] = "Hechizo de ayuda"
L["Heroic"] = "Heroico"
L["Holy"] = "Sagrado"
L["How many days before removing all data on a player. This includes comments and ratings, even your own!"] = "Cuantos dias antes de borrar todos los datos de un jugador. Esto incluye comentarios y calificaciones , incluso las tuyas!!!"
L[ [=[How many days before talents/experience/equipment should be pruned, notes will be kept!

If the player has no notes or rating on them, all data is removed.]=] ] = [=[Cuantos dias antes de que se borren los talentos/experiencia/equipo, las notas se guardaran!

]=]
L["How many inspects to save"] = "Cuantas inspecciones guardar"
L["Icecrown Citadel"] = "Ciudadela Corona de Hielo"
L["If you leave a rating on somebody of 2 or less, the next time you group with them you will get a warning in chat."] = "Si tu dejas una calificacion en alguien de 2 o menos, la siguiente vez que estes en grupo con ellos se te avisara por el chat"
L["Ignore below level"] = "Ignorar por debajo del nivel"
L["Ignore data older than (days)"] = "Ignorar datos mas antiguos que (dias)"
L["Inexperienced"] = "Sin experiencia"
L["Inspecting only in an instance"] = "Inspeccionar solo en una instancia"
L["Inspection"] = "Inspeccion"
L["Inspect queue empty"] = "Cola de inspeccion vacia"
L["Instead of listing item link when viewing overall status, you'll instead see the name of the slot."] = "En lugar de listar el enalce del objeto cuando se ve la situacion general, tu veras en su lugar el nombre de la posicion."
L["Integrate tooltips"] = "Integrar pistas"
L["Integrate window"] = "Integrar ventana"
L["Item #%d not in cache"] = "Objeto #%d no en cache"
L["Item levels <= %d"] = "Niveles de objeto <= %d"
L["Koralon the Flame Watcher"] = "Koralon el vigilante de fuego"
L["Koralon, Vault"] = "Koralon ,Camara"
L["Left Click - Open player/target information"] = "Click Izquierdo - abre la informacion del jugador/Blanco"
L["Loading"] = "Cargando"
L["Loading data"] = "Cargando datos"
L["magical heals"] = "curaciones magicas"
L["Main/alt experience"] = "experiencia del Main /alter "
L[ [=[Main/alt experience is a way of letting other Elitist Group users see that you have experience in dungeons on more than one character. By setting a main, when people inspect your alt they will see your experience on both your main and alt. Your main will remain anonymous, only the experience data is shown to other users.
This will only show up for people who inspect you.]=] ] = [=[La experiencia del Main/alter es un modo de dejar a otros usuarios de Elitist Group ver que tienes experiencia en mazmorras con mas de un personaje. Estableciendo un main, cuando la gente te inspeccione en tu alter vera tu experiencia en los dos, tu main y tu alter. Tu main permancera anonimo , solo los datos de experiencia se mostrara a otros usuarios.
]=]
L["Mains experience on left, %s on right"] = "Experiencia del main en la izquierda, %s a la derecha"
L["Make %s my main"] = "Hacer /s mi main"
L["Malygos"] = "Malygos"
L["Marksmanship"] = "Punteria"
L["Match all filters"] = "Hacer coincidir todos los filtros"
L[ [=[Match all item level, gear, enchant and gem filters to report.

If unchecked, only have to match one.]=] ] = [=[Hacer coincidir todos los filtros de  niveles de objeto, equipo, encantamiento y gemas en el informe.

Si no se marcan , solo debera coincidir uno de ellos.]=]
L["Melee (All)"] = "Mele (todos)"
L["melee and ranged"] = "Mele y a distancia"
L["melee or range"] = "mele o a distancia"
L["n%-\"(.-)\""] = "n%-\"(.-)\""
L["Name"] = "Nombre"
L["Naxxramas"] = "Naxxramas"
L["Nearly-experienced"] = "Casi experimentado"
L["No"] = "No"
L[" (no belt buckle)"] = "(no hay ranura de cinturon)"
L["Nobody in your group matched the entered filters."] = "Nadie en tu grupo coincide con los filtros introducidos"
L["No channel selected"] = "Ningun canal seleccionado"
L["No comment"] = "Sin comentarios"
L["No data found for %s, and an inspection is pending. You'll have to wait a second and try again."] = "No hay datos para %s, y una inspeccion esta pendiente. Tienes que esperar un segundo e intentar de nuevo"
L["No data found on group, you might need to wait a minute for it to load."] = "No se han encontrado datos en el grupo, podrias necesitar esperar un minuto para que se descarguen."
L["No enchants found"] = "No hay encantamientos"
L["No enchants found."] = "Ningun encantamiento encontrado"
L["No filters are enabled, nothing to report based off of."] = "No se han habilitado filtros, no hay nada sobre lo que hacer el informe"
L["No filters setup, you need at least one to report."] = "No se han establecido filtros, no necesitas almenos uno para hacer el informe"
L["No gems found."] = "No se han encontrado gemas"
L["No gems found. Possibly due to a data error, but most likely they do not have any."] = "No hay gemas. Posiblemente debido a un error de datos, pero lo mas seguro es que no tenga ninguna"
L["No item equipped"] = "Ningun objeto equipado"
L["No notes found"] = "Notas no encontradas"
L["No notes were found for this player."] = "No se encontraron notas de este jugador"
L["No player found for unit %s."] = "Ningun jugador encontrado para la unidad %s."
L["No rating data on this player found."] = "No hay datos de calificacion para este jugador"
L["Normal"] = "Normal"
L["No secondary spec"] = "No tiene spec secundaria"
L["Notes (%d)"] = "Notas (%d)"
L["Nothing is wrong with this players enchants!"] = "No hay nada mal en los encantamientos de este jugador!"
L["Nothing is wrong with this players equipment!"] = "No hay nada mal en el equipo de este jugador!"
L["Nothing is wrong with this players gems!"] = "No hay nada mal en las gemas de este jugador!"
L["Not rated"] = "No calificado"
L["officer"] = "oficial"
L["Officer"] = "Oficial"
L["Ok"] = "Ok"
L["Onyxia's Lair"] = "Guarida de Onixia"
L["Other players have left a note on this person."] = "Otros jugadores han dejado notas sobre esta persona"
L["party"] = "grupo"
L["Party"] = "Grupo"
L["Party channel"] = "Canal de Grupo"
L["periodic damage"] = "daño periodico"
L["Physical (All)"] = "Fisico (todos)"
L["Player info"] = "Informacion del jugador"
L["Play on alts all the time? Check out /eg config -> Main/alt experience to have your mains achievements carry over."] = "Juegas con alters todo el tiempo? Revisa /eg config -> Experiencia de Main/alter  para tener los logros de tu main contigo ."
L["Pops up the summary window when you first zone into an instance using the Looking for Dungeon system showing you info on your group."] = "Sacar la ventana de sumario cuando entres en la mazmorra usando el sistema de busqueda de mazmorra mostrandote la informacion de tu grupo."
L["Protection"] = "Proteccion"
L["Prune all data (days)"] = "Borrar todos los datos (dias)"
L["Prune basic data (days)"] = "Borrar datos basicos (dias)"
L["Purified/Shiny Shard of the Flame are only good if the player also has the \"of the Scale\" trinket."] = "Fragmento de la llama Lustroso/Purificado solo son buenos si el jugador tiene tambien el Fragmento de la Escama Lustroso/Purificado "
L["PVP"] = "PVP"
L["PVP/Elemental Shaman"] = "PVP/Shaman Elemental"
L["Queue: %d players left"] = "Cola: quedan %d jugadores"
L["raid"] = "banda"
L["Raid"] = "Banda"
L["Raid channel"] = "Canal de banda"
L["Raids"] = "Bandas"
L["ranged critical"] = "Critico a distancia"
L["Rated %d of %d"] = "Calificado %d de %d"
L["Rating"] = "Calificacion"
L["Remove"] = "Quitar"
L["Report"] = "Informe"
L["Report to channel %s"] = "Mandar informe al canal %s"
L["Requested gear from %s, this might take a second."] = "Pedido equipo desde %s . esto podria llevar un segundo "
L["Requesting Elitist Group database from %s. Keep in mind this is hard throttled at once per hour."] = "Pidiendo la base de datos de Elitist Group de %s. Ten en mente que esto se limita a una vez por hora."
L["Requesting Elitist Group databases from everyone in your guild, this could take a while. Keep in mind this is hard throttled at once per hour."] = "Pidiendo Base de datos de Elitits Group de todo el mundo de tu hermandad. esto podria llevar un rato. Ten en mente que esto se limita a una vez por hora."
L["Requesting Elitist Group notes from everyone in your guild, this could take a minute. Keep in mind this is hard throttled at onnce every 30 minutes."] = "Pidiendo notas de Elitist Group de todos los de tu hermandad, esto puede llevar un minuto. Ten en mente que esta limitado a una vez cada 30 minutos."
L["Requesting Elitist Group notes from %s. Keep in mind this is hard throttled at once every 30 minutes."] = "Pidiendo notas de Elitist Group de %s. Ten en mente que esto es limitado a una vez cada 30 minutos."
L["Reset all user data."] = "Resetear todos los datos de usuario"
L["Restoration"] = "Restauracion"
L["Retribution"] = "Retribucion"
L["Revitalizing meta requires a Solace of the Fallen/Defeated trinket for it to be a good meta gem for Restoration Shamans."] = "La meta Revitalizante requiere un abalorio Consuelo de los caídos/Derrotados para ser una buena meta para Shaman Resto"
L["Right Click - Open summary for your party"] = "Click Derecho- Abre sumario para tu grupo"
L["Right Click - Open summary for your raid"] = "Click Derecho . Abre sumario para tu banda"
L["Role"] = "Rol"
L["root duration"] = "Duracion de Raices"
L["run speed"] = "Velocidad de carrera"
L["s%-\"(.-)\""] = "s%-\"(.-)\""
L["Sartharion"] = "Sartharion"
L["Save foreign server data"] = "Salvar datos de servidor externo"
L["%s - |cffffffff%d|r missing |4gem:gems;"] = "%s - |cffffffff%d|r falta(n) |4gema:gemas;"
L["%s - |cffffffff%s|r"] = "%s - |cffffffff%s|r"
L["%s - |cffffffff%s|r gem"] = "%s - |cffffffff%s|r gema"
L["%s - |cffffffff%s|r item"] = "%s - |cffffffff%s|r objeto"
L["%s - |cffffffff%s|r quality gem"] = "%s - |cffffffff%s|r gema de calidad"
L["%s - %d-man %s (%s)"] = "%s - %d-persona %s (%s)"
L["%s does not have any users to send you."] = "%s no tiene ningun usuario para enviarte"
L["(%s%d|r) Gear [|cff%02x%02x00%d%%|r]"] = "(%s%d|r) Equipo [|cff%02x%02x00%d%%|r]"
L["Search..."] = "Buscando...."
L["Secondary"] = "Secundaria"
L[ [=[Seen as %s - %s:
|cffffffff%s|r]=] ] = [=[Visto como  %s - %s:
|cffffffff%s|r]=]
L["%s either disabled database syncing, or you are not on their trusted list."] = "%s o ha deshabilitado la sincronizacion de base de datos o tu no estas en su lista de confianza"
L["Select all"] = "Seleccionar todo"
L["Semi-experienced"] = "Semi-experimentado"
L["Sent your gear to %s! It will arrive in a few seconds"] = "Enviar tu equipo a %s! llegara en pocos segundos"
L["Set role as damage."] = "Establacer rol como daño"
L["Set role as healer."] = "Establecer rol como sanador"
L["Set role as tank."] = "Establecer role como tanque"
L["Shadow"] = "Sombra"
L[ [=[Should you want finer control over who is on the trusted list, you can manually add players here.

Stored by faction/realm]=] ] = [=[Si quieres afinar el control sobre quien esta en tu lista de confianza. puedes manualmente añadir jugadores aqui.

]=]
L["Show rating after dungeon"] = "Mostrar calificacion despues de la mazmorra"
L["Show slot names"] = "Mostrar casilla de nombres"
L["Show summary on dungeon start"] = "Mostrar sumario al empezar la mazmorra"
L["silence duration"] = "Duracion de Silencio"
L["Slash commands (/eg, /elitistgroup)"] = "Comandos con barra (/eg, /elitistgroup)"
L["%s - Missing belt buckle or gem"] = "%s - Falta ranura de cinturon o gema"
L["spell damage"] = "daño de hechizo"
L["%s, %s"] = "%s, %s"
L["%s - %s, level %s %s."] = "%s - %s, Nivel %s &s."
L["%s - %s, level %s, unknown class."] = "%s - %s, Nivel %s &s, Clase desconocida"
L["%s, %s role."] = "%s, %s rol"
L[ [=[%s, %s role.

This player has not spent all of their talent points!]=] ] = [=[%s, %s role.

Este jugador no ha gastado todos sus puntos de talentos!!]=]
L["%s: %s - %s, level %s %s"] = "%s: %s - %s, nivel %s %s"
L["%s: %s - %s, level %s, unknown class"] = "%s: %s - %s, nivel %s, clase desconocida"
L["%s (Trusted)"] = "%s Fiable"
L["stun duration"] = "Duracion de aturdimiento"
L["stun resistance"] = "Resistencia al aturdimiento"
L["Subtlety"] = "Sutileza"
L["Suggested dungeons"] = "Mazmorras sugeridas"
L["Suitational (Caster)"] = "Posicional (caster)"
L["Suitational (Healer)"] = "Posicional (sanador)"
L["%s - Unenchanted"] = "%s - sin encantar"
L["%s, unknown class"] = "%s, clase desconocida"
L["%s (Untrusted)"] = "%s No fiable"
L["Survival"] = "Supervivencia"
L["T10 Dungeons"] = "Mazmoras T10"
L["T7 Dungeons"] = "Mazmorras T7"
L["T9 Dungeons"] = "Mazmorras T9"
L["Talents unavailable"] = "Talentos no disponibles"
L["Tank"] = "Tanque"
L["Tank/DPS"] = "Tanque/DPS"
L["Tank/PVP"] = "Tanque/PVP"
L["Tank/Ranged DPS"] = "Tanque/DPS a distancia"
L["Terrible"] = "Terrible"
L["The data you see should be accurate. However, it is not guaranteed as it is from an unverified source."] = "Los datos que ves deberian ser correctos. Sin embargo, no se garantiza porque provienen de un origen no verificado"
L["The player has not purchased dual specialization yet."] = "El jugador no ha comprado la doble especializacion aun."
L["The Ruby Sanctum"] = "El Sagrario Rubí"
L["Toravon the Ice Watcher"] = "Toravon el vigilante de hielo"
L["Trial of the Crusader"] = "Prueba del Cruzado"
L["Trial of the Grand Crusader"] = "Prueba del Gran Cruzado"
L["Trust friends"] = "Confiar en amigos"
L["Trust guild members"] = "Confiar en miembros de la hermandad"
L["Trust list and addon communication options can be found in the menu to your left."] = "La lista de confianza y las opciones de comunicacion se encuentran en el menu a tu izquierda"
L[ [=[Trust list is an easy way for you to see at a glance how much faith can be placed in data. It is also used for determining whether somebody can send or receive database and full note requests.
Both parties have to be on each others trust lists.]=] ] = [=[La lista de confianza es una forma facil para que veas de un vistazo cuanta fe se puede tener en los datos. Se usa tambien para determinar cuando alguien puede enviar o recibir bases de datos y peticiones de todas las notas.
Ambos grupos tiene que estar cada uno en la lista de confianza del otro]=]
L["Trust management"] = "Gestion de confianza"
L["Ulduar"] = "Ulduar"
L["Unchecking this disables other Elitist Group users from requesting your gear without inspecting."] = "Desmarcar esto impide a otros usuarios de Elitits Group pedir tu equipo sin inspeccionar"
L[ [=[Unchecking this will completely disable all communications in Elitist Group.

You will not be able to send or receive notes on players, or check gear without inspecting.]=] ] = [=[Desmarcar esto deshabilitara completamente todas las comunicaciones de Elititst Group.

No seras capaz de enviar o recibir notas de jugadores o verificar su equipo sin inspeccionarle.]=]
L["Unholy"] = "Profano"
L["Unknown"] = "Desconocido"
L["URL"] = "URL"
L["User data not available yet."] = "Datos de usuario no disponibles aun"
L["User data pruned"] = "Datos de usuario depurados"
L["User %s is or went offline during syncing."] = "El usuario %s esta desconectado o se desconecto durante la sincronizacion"
L["Vault of Archavon"] = "Camara de Archavon"
L["View"] = "Ver"
L["View info on %s."] = "Ver informacion sobre &s."
L["View the group on ElitistArmory.com"] = "Ver el grupo en ElitistArmory.com"
L["View the player on ElitistArmory.com"] = "Ver al jugador en ElititistArmory.com"
L["Welcome! Type /elitistgroup help (or /eg help) to see a list of available slash commands."] = "Bienvenido! Escribe /elitistgroup help ( o /eg help) para ver una lista de comandos"
L["When automatically scanning your group, this is the number of inspects that will be saved so you can still inspect other people while the scan runs.|n|nThe more inspects you keep, the longer a scan will take."] = "Cuando escaneas automanticamente a tu grupo, este es el numero de inspecciones que seran guardadas asi podras tambien inspeccionar a otros mientras se escanea.|n|n Cuantas mas inspecciones mantengas, mas tardara el escaneo."
L["When /eg summary is closed, the group inspect queue will always be processed.|n|nUnchecking this means the inspect queue is reset when /eg summary is closed."] = "Cuando se cierra /eg summary , la cola de inspeccion de grupo siempre sera procesada.|n|nDesmarcar esto significa que la cola de inspeccion es reseteada cuando /eg summary se cierra."
L["when hit"] = "cuando pega"
L[ [=[Whether enchants should be included in the report.

When set, it will show people with a percentage of bad enchants higher than the entered amount.]=] ] = [=[Definir si los encantamientos deberian ser incluidos en el informe

Cuando se marca, mostrara a la gente con un porcentaje de encantamientos incorrectos mas alto que la cantidad entrada]=]
L[ [=[Whether equipment should be included in the report.

When set, it will show people with a percentage of bad gear higher than the entered amount.]=] ] = [=[Definir si el equipo deberia ser incluido en el informe

Cuando se marca, mostrara a la gente con un porcentaje de equipo incorrecto mas alto que la cantidad introducida]=]
L["Whether item level should be included in the report, or only show average item levels below the selected value."] = "definir si el nivel de objeto deberia ser incluido en el informe , o solo mostrar el nivel medio de objetos por debajo del valor seleccionado"
L["While the player data should be accurate, it is not guaranteed as the source is unverified."] = "Aunque los datos del jugador deberian ser correctos no se garantiza porque el origen no ha sido verificado"
L["Yes"] = "Si"
L["You are not inside chat channel #%d, can't send report."] = "No estas dentro del canal de chat #%d, no se puede enviar el informe"
L["You can choose which channels communication is accepted over. As long as communications are enabled, whisper is accepted. Communications are queued while in combat regardless."] = "Tu puedes elegir que caneles de comunicacion son aceptados. Durante el tiempo que las comunicaciones esten establecidas los susurros son aceptados. Las comunicaciones se pone en cola mientras este en combate dure lo que dure este."
L["You can edit or add a note on this player here."] = "Puedes editar o añadir una nota para este jugador aqui"
L["You cannot request the database of everyone in your guild without being a guild!"] = "No puedes pedir la base de datos de alguien de tu hermandad sin estar en una hermandad!"
L["You cannot request the notes of everyone in your guild without being a guild!"] = "No puedes pedir las notas de todo el mundo de tu hermandad si no estas en una hermandad!"
L["You can only send a report once every 60 seconds."] = "Solo puedes enviar un informe cada 60 segundos"
L["You did not set a channel to report to."] = "No pusiste el canal por el que enviar el informe"
L["You have not set a main yet."] = "Tu no has establecido tu personaje main"
L["You have to add %s to your trusted list before you can use this."] = "Tienes que añadir a %s a tu lista de confianza antes de que puedas usar esto."
L["You have to enter a name for this to work."] = "Tenes que escribir un nombre para que esto funcione."
L["You must be in a group to use this."] = "Debes estar en un grupo para usar esto"
L["You need to be in a guild to output to this channel."] = "Necesitas estar en una hermandad para sacar informacion en ese canal"
L["You need to be in a party to output to this channel."] = "Necesitas estar en grupo para mostrar informacion en ese canal"
L["You need to be in a raid to output to this channel."] = "Necesitas estar en una banda para mostrar informacion en ese canal"
L["You need to currently be in a group, or have been in a group to use the rating tool."] = "Necesitas esta actualmente en un grupo, o haber estado en un grupo para usar la herramienta de calificacion"
L["You need to enable database syncing in /eg config -> Addon communication to use this."] = "Necesitas habilitar la sincronizacion de base de datos en /eg config -> Comunicacion de addon para usar esto"
L["Your main is currently: %s."] = "Tu main es actualmente %s"
L[ [=[You wrote %s ago:
|cffffffff%s|r]=] ] = [=[Tu escribiste %s hace:
|cffffffff%s|r]=]

local ElitistGroup = select(2, ...)
ElitistGroup.L = setmetatable(L, {__index = ElitistGroup.L})
