if( GetLocale() ~= "esMX" ) then return end
local L = {}
L["<1 minute old"] = "viejo por menos que un minuto."
L["Addon communication"] = "comunicación de addons."
L["Affliction"] = "Aflicción"
L["All"] = "Todo (Todos if it's plural or refers to everyone)"
L["Allow gear requests"] = "Permitir solicitudes de armadura." -- Needs review
L["Always bad"] = "Siempre malo (mala if female)"
L["Arcane"] = "Arcano"
L["Archavon the Stone Watcher"] = "Archavon el Vigía de Piedra"
L["Archavon, Vault"] = "Archavon, Cámara"
L["Arms"] = "Armas"
L["Assassination"] = "Asesinato"
L["Automatically requests notes on your group from other Elitist Group users. Only sends requests once per session, and you have to be in a guild."] = "Automaticamente pide para las notas de tu grupo de otros que usan Elitist Group.  Solo manda solicitudes una vez por sesión, y tienes que estar en una hermandad." -- Needs review
L["Auto request notes"] = "Automaticamente pedir para notas" -- Needs review
L["Balance"] = "Equilibrio"
L["Beast Mastery"] = "Maestría en Bestias"
L["Blood"] = "Sangre"
L["Combat"] = "Combate"
L["Comment"] = "Comentario"
L["Demonology"] = "Demonologia"
L["Destruction"] = "Destrucción"
L["Discipline"] = "Disciplina"
L[" (%d-man)"] = "(%d-jugadores)"
L["DPS (All)"] = "Daño"
L["DPS (Caster)"] = "Daño (Hechicero)"
L["DPS (Melee)"] = "Daño (Cuerpo a Cuerpo)"
L["DPS (Physical)"] = "Daño (Fisica)"
L["DPS (Ranged)"] = "Daño (A distancia)"
L["Dungeons"] = "Mazmorras"
L["Elemental"] = "Elemental"
L["Emalon the Storm Watcher"] = "Emalon el vigía de la Tormenta"
L["Emalon, Vault"] = "Emalon, Cámara"
L["Enchants"] = "encantación" -- Needs review
L["Enchants: |cffffffffThe player does not have any enchants|r"] = "Este jugador no tiene ningunas encantaciónes." -- Needs review
L["Enhancement"] = "Mejora"
L["Equipment"] = "Equipamiento"
L["Equipment: |cffffffff%d bad items found|r"] = "Equipamiento:  |cffffffff%d Malas itemas encontradas|r" -- Needs review
L["Experience"] = "Experencia"
L["Feral"] = "Combate Feral"
L["Fire"] = "Fuego"
L["Frost"] = "Escarcha"
L["Fury"] = "Furia"
L["Gems"] = "Gemas"
L["Gems: |cffffffff%d bad|r"] = "Gemas: |cffffffff%d malas|r"
L["Gems: |cffffffffFailed to find any gems|r"] = "Gemas:  |cffffffffNo podia encontrar ningunas gemas.|r" -- Needs review
L["Gems: |cffffffffNo sockets|r"] = "Gemas:  |cffffffffNingunas Ranuras|r"
L["General"] = "General"
L["Guild channel"] = "Canal de la Hermandad" -- Needs review
L["Hard"] = "Dificil"
L["Healer"] = "Sanador"
L["Healer (All)"] = "Sanador (Todos)"
L["Healer/DPS"] = "Sanador/Daño"
L["Heroic"] = "Heroica"
L["Holy"] = "Sagrado"
L["Icecrown Citadel"] = "Ciudadela Corona del Hielo"
L["Ignore below level"] = "Ignorar alguien bajo de nivel" -- Needs review
L["Koralon the Flame Watcher"] = "Koralon el vigía de las Llamas"
L["Koralon, Vault"] = "Koralon, Cámara"
L["Loading"] = "Cargando"
L["Loading data"] = "Cargando los datos"
L["Malygos"] = "Malygos"
L["Marksmanship"] = "Punteria"
L["Melee (All)"] = "Cuerpo a Cuerpo (Todos)"
L["Name"] = "Nombre"
L["Naxxramas"] = "Naxxramas"
L["No comment"] = "Ningun comentario"
L["No enchants found."] = "Ningunas encantaciónes encontradas." -- Needs review
L["No item equipped"] = "Ninguna itema equipada."
L["No notes found"] = "Ningunas notas encontradas."
L["No notes were found for this player."] = "Ningunas notas se encontraron para este jugador."
L["No player found for unit %s."] = "Ningun jugador encontrado para unidad %s."
L["Normal"] = "Normal"
L["Notes (%d)"] = "Notas"
L["Nothing is wrong with this players enchants!"] = "¡No hay nada que es mala con las encantaciónes de este jugador!" -- Needs review
L["Nothing is wrong with this players equipment!"] = "¡No hay nada que es malo con el equipamiento de este jugador!" -- Needs review
L["Nothing is wrong with this players gems!"] = "¡No hay nada que es mala con las gemas de este jugador!" -- Needs review
L["Onyxia's Lair"] = "La Guarida de Onyxia."
L["Other players have left a note on this person."] = "Otros jugadores han hecho una nota de esta persona."
L["Party channel"] = "Canal de Grupo"
L["Physical (All)"] = "Fisica (Todos)" -- Needs review
L["Player info"] = "Información del Jugador"
L["PVP"] = "JcJ"
L["%s - |cffffffff%s|r gem"] = "gema"
L["%s - |cffffffff%s|r quality gem"] = "gema de buena calidad"
L["%s - Missing belt buckle or gem"] = "No tiene hebilla del cinturón o gemas." -- Needs review
L["%s - %s, level %s %s."] = "%s - %s, nivel %s %s"
L["%s - %s, level %s, unknown class."] = "%s - %s, nivel %s, clase desconocido"
L["%s, %s role."] = "función"
L[ [=[%s, %s role.

This player has not spent all of their talent points!]=] ] = "¡Este jugador no ha gastado todos sus puntos de talentos!" -- Needs review
L["%s - Unenchanted"] = "No está encantado." -- Needs review

local ElitistGroup = select(2, ...)
ElitistGroup.L = setmetatable(L, {__index = ElitistGroup.L})
