if( GetLocale() ~= "frFR" ) then return end
local L = {}
L["--"] = "--"
L["---"] = "---"
L["<1 minute old"] = "Il y a <1 minute"
L["Active"] = "Actif"
L["Add"] = "Ajout."
L["Add an user manually"] = "Ajout manuel d'un utilisateur"
L["Addon communication"] = "Communications de l'addon"
L["Adds summary information to the main inspection window."] = "Ajoute un condensé des informations à la fenêtre d'inspection principale."
L["Adds tooltips when mousing over inspected items indicating the items type, and if the gems and enchants pass."] = "Ajoute des bulles l'aide lors du survol de la souris des objets inspectés, indiquant le type d'objet et si les gemmes et enchantements sont corrects."
L["Affliction"] = "Affliction"
L["After completing a dungeon through the Looking For Dungeon system, automatically popup the /rate frame so you can set notes and rating on your group members."] = "Après avoir terminé un donjon via le système de Recherche de donjon, fait apparaître automatiquement le cadre /rate afin que vous puissez définit les notes et les évaluations des membres de votre groupe."
L["Alerts you in chat when you receive new notes or gear information from somebody."] = "Vous prévient dans la fenêtre de discussion quand vous recevez de nouvelles notes ou des informations d'équipement de quelqu'un."
L["Alert when grouped with low rated players"] = "Prévenir qd groupé avec des joueurs mal notés"
L["All"] = "Tous"
L["Allow database syncing"] = "Autoriser synch. BdD"
L["Allow gear requests"] = "Autoriser les requêtes"
L["Allows both you and other people on your trusted list to send and request your database of users."] = "Vous permet, ainsi qu'aux personnes présentes dans votre liste de confiance, d'envoyer et de recevoir les bases de données des utilisateurs."
L["ALT + Left Click - Open report window for group"] = "ALT + Clic-gauche - ouvre la fenêtre de rapport pour le groupe"
L["ALT + Right Click - Open rating window for party"] = "Alt + clic-droit - ouvre la fenêtre d'évaluation de votre groupe"
L["ALT + Right Click - Open rating window for raid"] = "ALT + clic-droit - ouvrir la fenêtre d'évaluation du raid"
L["Always bad"] = "toujours mauvais"
L["Always process group queue"] = "Tj traiter file du groupe"
L["Announce synced data"] = "Annoncer les synchro."
L["Any data from another server will not be saved, this includes notes! If you would like most of the data to be pruned but notes kept intact change basic pruning and leave this on."] = "Toute données provenant d'un autre serveur ne sera pas sauvegardé, y compris les notes ! Si vous souhaitez jetter la plupart des données mais garder les notes, changez le temps de vie des données basiques et laissez ceci activé."
L["Any data older than the set number will not be synced."] = "Toutes les données plus vieilles que le nombre de jours définit ne seront pas synchronisées."
L["Arcane"] = "Arcane"
L["Archavon the Stone Watcher"] = "Archavon le Gardien des pierres"
L["Archavon, Vault"] = "Archavon, Caveau"
L["Are you sure you want to reset ALL user data recorded, including notes?"] = "Êtes-vous sûr de vouloir réinitialiser toutes les données utilisateurs enregistrées, en ce compris les notes ?"
L["armor by"] = "l'Armure par"
L["armor for"] = "à l'armure"
L["Arms"] = "Armes"
L["As of 3.3.5, Blizzard has started to throttle inspections to 6 inspections every ~10 seconds.|n|nElitist Group has been updated to account for this, but you may see throttle messages when using /eg, group scans will also be slower. A new option has been added in /eg config to save X amount of inspections when scanning.|n|nYou can still use Elitist Armory to check groups without the throttle limit.|n|n|cffff2020Warning!|r|nGearscore has a habit of sending a higher than normal amount of inspect requests, disabling it is recommended.|nTipTop and other tooltip addons that show talents will also contribute to the limit.|n|nYou will only see this message once."] = "Depuis la 3.3.5, Blizzard a commencé à limiter les inspections à 8 inspections toutes les ~10 secondes.|n|nElitist Group a été mis à jour pour tenir compte de cela, mais vous risquez de voir des messages de limitation lors de l'utilisation de /eg, et les analyses de groupe seront également plus lentes. Une nouvelle option a été ajoutée dans /eg config afin de mettre de côté X inspections lors de l'analyse.|n|nVous pouvez toujours utiliser Elitist Armory pour vérifier vos groupes sans limitations.|n|n|cffff2020Attention !|r|nGearscore a pour habitude d'envoyer un nombre anormalement élevé de requêtes d'inspection, il est conseillé de le désactiver.|nTipTop et d'autres addons modifiant les bulles d'aide qui affichent les talents contribuent également à atteindre rapidement cette limite.|n|nVous ne verrez ce message qu'une seule fois."
L["Assassination"] = "Assassination"
L["Automatically"] = "Automatismes"
L["Automatically requests main experience (limited at once per an hour) when inspecting."] = "Demande automatiquement l'expérience du personnage principal (limité à une fois par heure) lors de l'inspection."
L["Automatically requests notes on your group from other Elitist Group users. Only sends requests once per session, and you have to be in a guild."] = "Lance automatiquement une requête de notes concernant votre groupe aux autres utilisateurs de Elitist Group. L'envoi de requête ne se fait qu'une fois par session, et uniquement si vous êtes dans une guilde."
L["Automatically trust all guild members, if you are in a guild."] = "Fait automatiquement confiance à tous les membres de votre guilde (si vous en avez une)."
L["Automatically trusts all players on your friends list."] = "Fait automatiquement confiance à tous les joueurs présents dans votre liste des amis."
L["Auto request main experience"] = "Demander auto. expérience du perso. principal"
L["Auto request notes"] = "Demander auto. notes"
L["Average"] = "Moyenne"
L["[average ilvl]"] = "[ilvl moyen]"
L["average item level below %d"] = "niveau moyen d'objet en dessous de %d"
L["Average item level of the players equipment."] = "Le niveau d'objet moyen de l'équipement du joueur."
L["Average rating %.2f of %d, rated %d times."] = "Évaluation moyenne de %.2f sur %d, évalué %d fois."
L["[bad enchants]"] = "[mauvais enchantements]"
L["[bad equipment]"] = "[mauvais équipement]"
L["[bad gems]"] = "[mauvaises gemmes]"
L["Balance"] = "Équilibre"
L["Battleground channel"] = "Canal CdB"
L["Beast Mastery"] = "Maîtrise des bêtes"
L["Blood"] = "Sang"
L["c%-\"(.-)\""] = "c%-\"(.-)\""
L["Cannot find record of %s in your saved database."] = "Impossible de trouver l'enregistrement |2 %s dans votre base de données sauvegardées."
L["Cannot find URL for this player, don't seem to have name, server or region data."] = "Impossible de trouver d'URL pour ce joueur : données concernant le nom, le serveur ou la région introuvable."
L["Cannot inspect %s yet, you have to wait %.1f seconds before you can inspect again."] = "Impossible d'inspecter %s pour le moment, vous devez attendre %.1f secondes avant de pouvoir inspecter à nouveau."
L["Caster (All)"] = "Caster (Tous)"
L["Caster (Spirit)"] = "Caster (Esprit)"
L["|cff%02x%02x00%d|r avg, %d-man (%s)"] = "|cff%02x%02x00%d|r en moy, à %d (%s)"
L["[|cff%02x%02x00%d%%|r] Enchants"] = "[|cff%02x%02x00%d%%|r] Enchantements"
L["[|cff%02x%02x00%d%%|r] Equipment (%s%d|r)"] = "[|cff%02x%02x00%d%%|r] Équipement (%s%d|r)"
L["[|cff%02x%02x00%d%%|r] Gems"] = "[|cff%02x%02x00%d%%|r] Gemmes"
L["[|cff%02x%02x00%d%%|r] [%s%d|r] Equipment"] = "[|cff%02x%02x00%d%%|r] [%s%d|r] Équipement"
L["|cfffed000Item Type:|r %s%s"] = "|cfffed000Type d'objet :|r %s%s"
L["[|cffff20200%|r] Enchants"] = "[|cffff20200%|r] Enchantements"
L["[|cffff20200%|r] Gems"] = "[|cffff20200%|r] Gemmes"
L["|cffff2020%d unspent |4point:points;|r"] = "|cffff2020%d |4point non placé:points non placés;|r"
L["|cffff2020%d unspent|r (Secondary)"] = "|cffff2020%d |4non placée:non placées;|r (Secondaire)"
L["|cffff2020Warning!|r %s is in your group, you rated them %d"] = "|cffff2020Attention !|r %s est dans votre groupe et vous l'avez évalué(e) à %d"
L["|cffff2020Warning!|r %s is in your group, you rated them %d for: %s"] = "|cffff2020Attention !|r %s est dans votre groupe et vous l'avez évalué(e) à %d avec comme note : %s"
L[ [=[
|cffffffffAND|r
]=] ] = [=[
|cffffffffET|r
]=]
L[ [=[
|cffffffffOR|r
]=] ] = [=[
|cffffffffOU|r
]=]
L["|cffffffff%s|r %s, %s role."] = "|cffffffff%s|r %s, rôle de %s."
L[ [=[|cffffffff%s|r %s, %s role.

The player has not spent %d talent points.]=] ] = [=[|cffffffff%s|r %s, rôle de %s.

Ce joueur n'a pas placé %d |4point de talent:points de talent;.]=]
L[ [=[|cffffffff%s|r %s, %s role.

The player put all of his talent points into one tree.]=] ] = [=[|cffffffff%s|r %s, rôle de %s.

Ce joueur a placé tous ses points de talent dans le même arbre.]=]
L["chance on melee and range"] = "chance lorsque vous réussissez un coup critique en mêlée ou à distance"
L["chance on melee attack"] = "chance lors des attaques de mêlée"
L["chance on melee or range"] = "chance lorsque vous touchez en mêlée ou à distance"
L["Channel to report Elitist Group summary to."] = "Définit le canal dans lequel le résumé de Elitist Group est envoyé."
L["Classes"] = "Classes"
L["Click to open and close the database viewer."] = "Clic gauche pour ouvrir et fermer le visionneur de base de données."
L["Click to view detailed information."] = "Clic gauche pour les informations détaillées."
L["Combat"] = "Combat"
L["Comment"] = "Commentaire"
L["Comment..."] = "Commentaire..."
L["Completed %s! Type /rate to rate this group."] = "%s terminé(e)(s) ! Tapez /rate pour évaluer ce groupe."
L["Could not calculate average item level, no data found."] = "Impossible de calculer le niveau d'objet moyen : données introuvables."
L[ [=[Current filters are all players who have:

]=] ] = [=[Les filtres actuels comprennent les joueurs qui ont :

]=]
L["Custom list"] = "Liste personnalisée"
L["<= %d"] = "<= %d"
L["> %d%%"] = "> %d%%"
L["%d |4day:days;"] = "%d |4jour:jours;"
L["%d |4day:days; old"] = "Il y a %d |4jour:jours;"
L["%d |4hour:hours;"] = "%d |4heure:heures;"
L["%d |4hour:hours; old"] = "Il y a %d |4heure:heures;"
L["%d |4minute:minutes;"] = "%d |4minute:minutes;"
L["%d |4minute:minutes; old"] = "Il y a %d |4minute:minutes;"
L["Database"] = "Base de données"
L["Data for this player is from a verified source and can be trusted."] = "Les données de ce joueur proviennent d'une source fiable."
L[ [=[Data has been pruned to save database space.

Perhaps you want to change prune settings in /eg config?]=] ] = [=[Des données ont été effacées afin de réduire la taille de la base de données.

Peut-être souhaitez-vous changer les paramètres d'effacement dans /eg config ?]=]
L["Data is loading, please wait."] = "Données en chargement, veuillez patienter."
L["%d average rating"] = "Évalué à %d en moy."
L[">= %d%% bad enchants"] = ">= %d%% de mauvais enchantements"
L["> %d%% bad gear"] = "> %d%% de mauvaise équipement"
L[">= %d%% bad gems"] = ">= %d%% de mauvaises gemmes"
L["deal damage"] = "infligez des dégâts"
L["Delete"] = "Suppr."
L["Demonology"] = "Démonologie"
L["Destruction"] = "Destruction"
L["Discipline"] = "Discipline"
L[" (%d-man)"] = " (%d joueurs)"
L[ [=[Do not abuse this!

Abuse will result in the feature being removed.]=] ] = [=[N'abusez pas de ceci !

Tout abus n'aura comme résultat que le retrait de cette fonctionnalité.]=]
L["Do not require players who are below the given level."] = "Ne se préoccupe pas des joueurs inférieurs au niveau indiqué."
L["Don't include"] = "Ne pas inclure"
L["Don't include enchants"] = "Ignorer enchantements"
L["Don't include gear"] = "Ignorer l'équipement"
L["Don't include gems"] = "Ignorer les gemmes"
L["Don't include item level"] = "Ignorer  niveau d'objet"
L["%d%% or more bad enchants"] = "%d%% ou plus de mauvais enchantements"
L["%d%% or more bad equipped items"] = "%d%% ou plus de mauvais objets équipés"
L["%d%% or more bad gems"] = "%d%% ou plus de mauvaises gemmes"
L["DPS (All)"] = "DPS (Tous)"
L["DPS (Caster)"] = "DPS (Caster)"
L["DPS, Caster"] = "DPS, caster"
L["DPS (Melee)"] = "DPS (Mêlée)"
L["DPS, Melee"] = "DPS, mêlée"
L["DPS (Physical)"] = "DPS (Physique)"
L["DPS (Ranged)"] = "DPS (À distance)"
L["DPS, Ranged"] = "DPS, à distance"
L["Dungeons"] = "Donjons"
L["%d unspent |4point:points;"] = "%d |4point non assigné:points non assignés;"
L[" (%d unused |4socket:sockets;)"] = " (%d |4châsse non utilisée:châsses non utilisées;)"
L["Edit"] = "Édit."
L["/eg config - Opens the configuration"] = "/eg config - ouvre la fenêtre de configuration"
L["/eg db [name] - Requests either everyones database or [name]s database if specified"] = "/eg db [nom] - demande soit la base de données de tout le monde, soit celle de [nom] si passé en argument"
L["/eg gear <name> - Requests gear from another Elitist Group user without inspecting"] = "/eg gear <nom> - demande l'équipement d'un autre utilisateur d'Elitist Group sans à avoir à l'inspecter"
L["/eg leader - Opens the specialized group manager/former UI"] = "/eg leader - ouvre l'IU spécialisée de formation/gestion de groupe"
L["/eg <name> - When <name> is passed opens up the player viewer for that person, otherwise it opens it on yourself"] = "/eg <nom> - ouvre le visionneur de joueur soit sur vous-même, soit sur <nom> si passé en argument"
L["/eg notes [name] - Requests all guild members notes on players, if [name] is passed requests notes FROM [name]"] = "/eg notes [nom] - demande soit les notes écrites par tous les membres de la guilde, soit celles écrites par [nom] si passé en argument"
L["/eg rate - Opens the rating panel for your group"] = "/eg rate - ouvre le panneau d'évaluation de votre groupe"
L["/eg report - Opens the reporting UI for sending to chat summaries on your group"] = "/eg report - ouvre l'interface de rapport pour envoyer au chat un résumé sur votre groupe"
L["/eg send <name> - Sends your gear to another Elitist Group user"] = "/eg send <nom> - envoie votre équipement à un autre utilisateur d'Elitist Group"
L["/eg summary - Displays the summary page for your party or raid"] = "/eg summary - affiche la fenêtre de résumé de votre groupe ou raid"
L["Elemental"] = "Élémentaire"
L["Elitist Group (%s): showing %d players, check out http://elitistarmory.com for more info. Format is, [name] (%s)"] = "Elitist Group (%s) : affichage de %d |4joueur:joueurs;.Rendez-vous sur http://elitistarmory.com pour plus d'infos. Format : [nom] (%s)"
L["Emalon the Storm Watcher"] = "Emalon le Guetteur d'orage"
L["Emalon, Vault"] = "Emalon, Caveau"
L["Enable comms"] = "Activer les communications"
L["Enabled channels"] = "Canaux activés"
L["Enchant"] = "Enchantement"
L["Enchant: |cffff2020[!]|r |cffffffffNone found|r"] = "Enchantement : |cffff2020[!]|r |cffffffffaucun trouvé|r"
L["Enchant: |cffff2020[!]|r |cffffffff%s|r enchant"] = "Enchantement : |cffff2020[!]|r enchantement |cffffffff%s|r"
L["Enchant: |cffffffffCannot enchant|r"] = "Enchantement : |cffffffffimpossible à enchanter|r"
L["Enchant: |cffffffffPass|r"] = "Enchantement : |cffffffffcorrect|r"
L["Enchants"] = "Enchant."
L["Enchants [|cff%02x%02x00%d%%|r]"] = "Enchant. [|cff%02x%02x00%d%%|r]"
L["Enchants [|cffff20200%|r]"] = "Enchant. [|cffff20200%|r]"
L["Enchants: |cffffffff%d bad|r"] = "Enchantements : |cffffffff%d mauvais|r"
L["Enchants: |cffffffffPass|r"] = "Enchantements : |cffffffffcorrects|r"
L["Enchants: |cffffffffThe player does not have any enchants|r"] = "Enchantements : |cffffffffle joueur n'a aucun enchantement|r"
L["Enhancement"] = "Amélioration"
L["Equipment"] = "Équipement"
L["Equipment: |cffffffff%d bad items found|r"] = "Équipement : |cffffffff%d |4mauvais objet trouvé:mauvais objets trouvés;|r"
L["Equipment: |cffffffffPass|r"] = "Équipement : |cffffffffcorrect|r"
L["Experience"] = "Expérience"
L["Experienced"] = "Expérimenté"
L["fear duration"] = "durée de peur"
L["Feral"] = "Farouche"
L["Fire"] = "Feu"
L["Frost"] = "Givre"
L["Fury"] = "Furie"
L["Gear"] = "Équip."
L["Gear received from %s."] = "Équipement reçu |2 %s."
L["Gems"] = "Gemmes"
L["Gems [|cff%02x%02x00%d%%|r]"] = "Gemmes [|cff%02x%02x00%d%%|r]"
L["Gems [|cffff20200%|r]"] = "Gemmes [|cffff20200%|r]"
L["Gems: |cffff2020[!]|r |cffffffff%d bad|r%s"] = "Gemmes : |cffff2020[!]|r |cffffffff%d |4mauvaise:mauvaises;|r%s"
L["Gems: |cffffffff%d bad|r"] = "Gemmes : |cffffffff%d mauvais|r"
L["Gems: |cffffffffFailed to find any gems|r"] = "Gemmes : |cffffffffÉchec de la récupération des gemmes|r"
L["Gems: |cffffffffNo sockets|r"] = "Gemmes : |cffffffffpas de châsse|r"
L["Gems: |cffffffffPass|r"] = "Gemmes : |cffffffffcorrectes|r"
L["Gems/Enchant"] = "Gemmes/Ench."
L["General"] = "Général"
L["Great"] = "Génial"
L["guild"] = "guilde"
L["Guild"] = "Guilde"
L["Guild channel"] = "Canal Guilde"
L["Hard"] = "Difficile"
L["harmful spell"] = "sort néfaste"
L["Healer"] = "Soigneur"
L["Healer (All)"] = "Soigneur (Tous)"
L["Healer/DPS"] = "Soigneur/DPS"
L["Healing Priest/Druid"] = "Druide/Prêtre soins"
L["Help"] = "Aide"
L["helpful spell"] = "sort bénéfique"
L["Heroic"] = "Héroïque"
L["Holy"] = "Sacré"
L["How many days before removing all data on a player. This includes comments and ratings, even your own!"] = "Définit le nombre de jours avant la suppression de toutes les données concernant un joueur. Ceci s'applique aux commentaires et aux évaluations, même aux vôtres !"
L[ [=[How many days before talents/experience/equipment should be pruned, notes will be kept!

If the player has no notes or rating on them, all data is removed.]=] ] = [=[Définit le nombre de joueurs avant que les données concernant les talents, l'équipement et l'expérience ne soient supprimées (les notes sont conservées).

Si le joueur n'a pas de note ou d'évaluation, toutes les données sont supprimées.]=]
L["How many inspects to save"] = "Nombre d'inspection à mettre de côté"
L["Icecrown Citadel"] = "Citadelle de la Couronne de glace"
L["If you leave a rating on somebody of 2 or less, the next time you group with them you will get a warning in chat."] = "Si vous évaluez quelqu'un à 2 ou moins, vous serez prévenu via la fenêtre de discussion la prochaine fois qu'il sera dans votre groupe."
L["Ignore below level"] = "Ignorer en dessous du nv"
L["Ignore data older than (days)"] = "Ignorer données > X jours"
L["Inexperienced"] = "Inexpérienté"
L["Inspecting only in an instance"] = "Inspection uniquement en instance"
L["Inspection"] = "Inspection"
L["Inspect queue empty"] = "File d'inspection vide"
L["Instead of listing item link when viewing overall status, you'll instead see the name of the slot."] = "Au lieu de lister les liens d'objet lors de la consultation du statut global, vous verrez à la place le nom des emplacements."
L["Integrate tooltips"] = "Intégrer aux bulles"
L["Integrate window"] = "Intégrer à la fenêtre"
L["Item #%d not in cache"] = "Objet #%d non présent dans le cache"
L["Item levels <= %d"] = "Niveau d'objet <= %d"
L["Koralon the Flame Watcher"] = "Koralon le Gardien des flammes"
L["Koralon, Vault"] = "Koralon, Caveau"
L["Left Click - Open player/target information"] = "Clic-gauche - ouvre la fenêtre d'informations concernant votre joueur/cible"
L["Loading"] = "Chargement"
L["Loading data"] = "Chargement des données"
L["magical heals"] = "soins magiques"
L["Main/alt experience"] = "Expérience main/reroll"
L[ [=[Main/alt experience is a way of letting other Elitist Group users see that you have experience in dungeons on more than one character. By setting a main, when people inspect your alt they will see your experience on both your main and alt. Your main will remain anonymous, only the experience data is shown to other users.
This will only show up for people who inspect you.]=] ] = "L'expérience main/reroll est un moyen de faire savoir aux autres utilisateurs de Elitist Group que vous avez de l'expérience dans les donjons sur plus d'un personnage. En définissant un personne principal, quand des joueurs inspecteront un de vos rerolls, ils verront votre expérience acquise sur votre reroll et sur votre personnage principal. Votre personnage principal restera anonyme, seules les données d'expérience sont affichées aux autres utilisateurs."
L["Mains experience on left, %s on right"] = "L'experience du perso. principal est à gauche, celle |2 %s sur la droite"
L["Make %s my main"] = "Faire |2 %s mon perso. principal"
L["Malygos"] = "Malygos"
L["Marksmanship"] = "Précision"
L["Match all filters"] = "Correspondre à tout"
L[ [=[Match all item level, gear, enchant and gem filters to report.

If unchecked, only have to match one.]=] ] = [=[Doit correspondre à tous les filtres (gemmes, enchantements, équipement et niveaux d'objet) pour être dans le rapport.

Si décoché, seule la correspondance à un des filtres est nécessaire.]=]
L["Melee (All)"] = "Mêlee (Tous)"
L["melee and ranged"] = "mêlée et à distance"
L["melee or range"] = "mêlée ou à distance"
L["n%-\"(.-)\""] = "n%-\"(.-)\""
L["Name"] = "Nom"
L["Naxxramas"] = "Naxxramas"
L["Nearly-experienced"] = "Presque expérimenté"
L["No"] = "Non"
L[" (no belt buckle)"] = " (pas de boucle de ceinture)"
L["Nobody in your group matched the entered filters."] = "Personne dans votre groupe ne correspond aux filtres utilisés."
L["No channel selected"] = "Aucun canal sélectionné"
L["No comment"] = "Sans commentaire"
L["No data found for %s, and an inspection is pending. You'll have to wait a second and try again."] = "Aucune donnée n'a été trouvé pour %, et une inspection est en attente. Attendez une seconde et essayez à nouveau."
L["No data found on group, you might need to wait a minute for it to load."] = "Aucunes données concernant votre groupe n'ont été trouvées ; attendez une minute le temps qu'elles se chargent."
L["No enchants found"] = "Aucun enchantement trouvé"
L["No enchants found."] = "Aucun enchantement détecté."
L["No filters are enabled, nothing to report based off of."] = "Aucun filtre n'est activé, il n'y a donc rien à rapporter."
L["No filters setup, you need at least one to report."] = "Aucun filtre paramétré ; vous devez en paramétrer au moins un pour faire un rapport."
L["No gems found."] = "Aucune gemme trouvée"
L["No gems found. Possibly due to a data error, but most likely they do not have any."] = "Aucune gemme trouvée. Peut-être dû à une erreur de données, mais plus certainement car il n'y en a aucune."
L["No item equipped"] = "Aucun objet équipé"
L["No notes found"] = "Aucune note trouvée"
L["No notes were found for this player."] = "Aucune note n'a été trouvée pour ce joueur."
L["No player found for unit %s."] = "Aucun joueur trouvé pour l'unité %s."
L["No rating data on this player found."] = "Aucune donnée d'évaluation n'a été trouvée concernant ce joueur."
L["Normal"] = "Normal"
L["No secondary spec"] = "Pas de spé. secondaire"
L["Notes (%d)"] = "Notes (%d)"
L["Nothing is wrong with this players enchants!"] = "Rien à signaler concernant les enchantements de ce joueur !"
L["Nothing is wrong with this players equipment!"] = "Rien à signaler concernant l'équipement de ce joueur !"
L["Nothing is wrong with this players gems!"] = "Rien à signaler concernant les gemmes de ce joueur !"
L["Not rated"] = "Non évalué"
L["officer"] = "officier"
L["Officer"] = "Officier"
L["Ok"] = "Ok"
L["Onyxia's Lair"] = "Repaire d'Onyxia"
L["Other players have left a note on this person."] = "D'autres joueurs ont laissé une note concernant cette personne."
L["party"] = "groupe"
L["Party"] = "Groupe"
L["Party channel"] = "Canal Groupe"
L["periodic damage"] = "dégâts périodiques"
L["Physical (All)"] = "Physique (Tous)"
L["Player info"] = "Infos sur le joueur"
L["Play on alts all the time? Check out /eg config -> Main/alt experience to have your mains achievements carry over."] = "Vous jouez très souvent sur des rerolls ? Jetez un oeil à /eg config -> Expérience main/reroll pour que les hauts faits de votre personnage principal soient reportés."
L["Pops up the summary window when you first zone into an instance using the Looking for Dungeon system showing you info on your group."] = "Affiche la fenêtre de résumé quand vous entrez pour la première fois dans une instance créée via l'outil de Recherche de donjon, affichant les informations concernant votre groupe."
L["Protection"] = "Protection"
L["Prune all data (days)"] = "Vie de toutes les données (jours)"
L["Prune basic data (days)"] = "Vie des données basiques (jours)"
L["Purified/Shiny Shard of the Flame are only good if the player also has the \"of the Scale\" trinket."] = "Fragment de la Flamme rutilant/purifiée est bien uniquement si le joueur a également le bijou \"de l'écaille\"."
L["PVP"] = "JcJ"
L["PVP/Elemental Shaman"] = "Chaman élémentaire/JcJ"
L["Queue: %d players left"] = "File : %d |4joueur restant:joueurs restants;"
L["raid"] = "raid"
L["Raid"] = "Raid"
L["Raid channel"] = "Canal Raid"
L["Raids"] = "Raids"
L["ranged critical"] = "coup critique à distance "
L["Rated %d of %d"] = "Évalué %d sur %d"
L["Rating"] = "Éval."
L["Remove"] = "Enlever"
L["Report"] = "Rapport"
L["Report to channel %s"] = "Rapporter sur le canal %s"
L["Requested gear from %s, this might take a second."] = "Équipement |2 %s demandé, cela peut prendre un peu de temps."
L["Requesting Elitist Group database from %s. Keep in mind this is hard throttled at once per hour."] = "Demande de la base de données Elitist Group |2 %s. Notez qu'il faudra attendre 1h avant d'être autorisé à redemander la base de données de cette personne."
L["Requesting Elitist Group databases from everyone in your guild, this could take a while. Keep in mind this is hard throttled at once per hour."] = "Demande de la base de données Elitist Group de tous les membres de la guilde. Cela peut prendre du temps. Notez qu'il faudra attendre 1h avant d'être autorisé à redemander les bases de données des membres de la guilde."
L["Requesting Elitist Group notes from everyone in your guild, this could take a minute. Keep in mind this is hard throttled at onnce every 30 minutes."] = "Demande des notes Elitist Group de tous les membres de la guilde. Cela peut prendre du temps. Notez qu'il faudra attendre 30min avant d'être autorisé à redemander les notes des membres de la guilde."
L["Requesting Elitist Group notes from %s. Keep in mind this is hard throttled at once every 30 minutes."] = "Demande des notes Elitist Group |2 %s. Notez qu'il faudra attendre 30min avant d'être autorisé à redemander les notes de cette personne."
L["Reset all user data."] = "Réinitialise toutes les données."
L["Restoration"] = "Restauration"
L["Retribution"] = "Vindicte"
L["Revitalizing meta requires a Solace of the Fallen/Defeated trinket for it to be a good meta gem for Restoration Shamans."] = "Une méta revitalisante nécessite un bijou Réconfort des défunts/des vaincus pour être une bonne méta-gemme pour chaman restauration."
L["Right Click - Open summary for your party"] = "Clic-droit - ouvre le résumé de votre groupe"
L["Right Click - Open summary for your raid"] = "Clic-droit - ouvre le résumé de votre raid"
L["Role"] = "Rôle"
L["root duration"] = "durée de ralentir et immobiliser"
L["run speed"] = "augmentation de la vitesse"
L["s%-\"(.-)\""] = "s%-\"(.-)\""
L["Sartharion"] = "Sartharion"
L["Save foreign server data"] = "Garder données serveurs étrangers"
L["%s - |cffffffff%d|r missing |4gem:gems;"] = "%s - |cffffffff%d|r |4gemme manquante:gemmes manquante;"
L["%s - |cffffffff%s|r"] = "%s - |cffffffff%s|r"
L["%s - |cffffffff%s|r gem"] = "%s - gemme |cffffffff%s|r"
L["%s - |cffffffff%s|r item"] = "%s - objet |2 |cffffffff%s|r"
L["%s - |cffffffff%s|r quality gem"] = "%s - gemme de qualité |cffffffff%s|r"
L["%s - %d-man %s (%s)"] = "%s - %3$s à %2$d joueurs (%s)"
L["%s does not have any users to send you."] = "%s n'a rien à vous envoyer."
L["(%s%d|r) Gear [|cff%02x%02x00%d%%|r]"] = "(%s%d|r) Équip [|cff%02x%02x00%d%%|r]"
L["Search..."] = "Rechercher..."
L["Secondary"] = "Secondaire"
L[ [=[Seen as %s - %s:
|cffffffff%s|r]=] ] = [=[Vu(e) en tant que %s - %s :
|cffffffff%s|r]=]
L["%s either disabled database syncing, or you are not on their trusted list."] = "%s a soit désactivé la synchronisation de la base de données, soit ne vous a pas ajouté dans sa liste de confiance."
L["Select all"] = "Tout sélec."
L["Semi-experienced"] = "Semi-experimenté"
L["Sent your gear to %s! It will arrive in a few seconds"] = "Équipement envoyé à %s ! Il arrivera à destination dans quelques secondes"
L["Set role as damage."] = "Définit son rôle comme étant DPS."
L["Set role as healer."] = "Définit son rôle comme étant soigneur."
L["Set role as tank."] = "Définit son rôle comme étant tank."
L["Shadow"] = "Ombre"
L[ [=[Should you want finer control over who is on the trusted list, you can manually add players here.

Stored by faction/realm]=] ] = [=[Si vous souhaitez affiner votre liste de confiance, vous pouvez ajouter des joueurs manuellement ici.

Stockés selon la faction/le royaume]=]
L["Show rating after dungeon"] = "Aff. évaluation à la fin"
L["Show slot names"] = "Aff. noms emplac."
L["Show summary on dungeon start"] = "Aff. résumé au début"
L["silence duration"] = "durée de silence"
L["Slash commands (/eg, /elitistgroup)"] = "Commandes slash (/eg, /elitistgroup)"
L["%s - Missing belt buckle or gem"] = "%s - boucle de ceinture manquante (ou sa gemme)"
L["spell damage"] = "dégâts des sorts"
L["%s, %s"] = "%s, %s"
L["%s - %s, level %s %s."] = "%s - %s, %4$s de niveau %3$s."
L["%s - %s, level %s, unknown class."] = "%s - %s, niveau %s, classe inconnue."
L["%s, %s role."] = "%s, rôle de %s."
L[ [=[%s, %s role.

This player has not spent all of their talent points!]=] ] = [=[%s, rôle de %s.

Ce joueur n'a pas placé tous ses points de talent !]=]
L["%s: %s - %s, level %s %s"] = "%s : %s - %s, %4$s de niveau %3$s"
L["%s: %s - %s, level %s, unknown class"] = "%s : %s - %s, niveau %s, classe inconnue"
L["%s (Trusted)"] = "%s (Fiable)"
L["stun duration"] = "durée de etourdir"
L["stun resistance"] = "résistance aux étourdissements"
L["Subtlety"] = "Subtilité"
L["Suggested dungeons"] = "Donjons suggérés"
L["Suitational (Caster)"] = "Situationnel (Caster)"
L["Suitational (Healer)"] = "Situationnel (Soigneur)"
L["%s - Unenchanted"] = "%s - pas enchanté"
L["%s, unknown class"] = "%s, classe inconnue"
L["%s (Untrusted)"] = "%s (Non fiable)"
L["Survival"] = "Survie"
L["T10 Dungeons"] = "Donjons T10"
L["T7 Dungeons"] = "Donjons T7"
L["T9 Dungeons"] = "Donjons T9"
L["Talents unavailable"] = "Talents indisponibles"
L["Tank"] = "Tank"
L["Tank/DPS"] = "Tank/DPS"
L["Tank/PVP"] = "Tank/JcJ"
L["Tank/Ranged DPS"] = "Tank/DPS à distance"
L["Terrible"] = "Affreux"
L["The data you see should be accurate. However, it is not guaranteed as it is from an unverified source."] = "Les données que vous voyez devraient être correctes. Cependant, cela n'est pas garanti car elles proviennent d'une source non vérifiée."
L["The player has not purchased dual specialization yet."] = "Le joueur n'a pas encore acheté la double spécialisation des talents."
L["The Ruby Sanctum"] = "Le sanctum Rubis"
L["Toravon the Ice Watcher"] = "Toravon la Sentinelle de glace"
L["Trial of the Crusader"] = "L'épreuve du croisé"
L["Trial of the Grand Crusader"] = "L'épreuve du grand croisé"
L["Trust friends"] = "Faire confiance aux amis"
L["Trust guild members"] = "Faire confiance à la guilde"
L["Trust list and addon communication options can be found in the menu to your left."] = "Les options concernant la liste de confiance et les communications de l'addon se trouvent dans le menu sur votre gauche."
L[ [=[Trust list is an easy way for you to see at a glance how much faith can be placed in data. It is also used for determining whether somebody can send or receive database and full note requests.
Both parties have to be on each others trust lists.]=] ] = "La liste de confiance est un moyen facile de voir du premier coup d'œil quelle crédibilité vous pouvez placer dans les données reçues. Elle peut également être utilisée pour déterminer les personnes pouvant envoyer ou recevoir les bases de données ainsi que les notes."
L["Trust management"] = "Liste de confiance"
L["Ulduar"] = "Ulduar"
L["Unchecking this disables other Elitist Group users from requesting your gear without inspecting."] = "Décochez ceci si vous ne souhaitez pas que les autres utilisateurs de Elitist Group ne demande votre équipement sans inspection."
L[ [=[Unchecking this will completely disable all communications in Elitist Group.

You will not be able to send or receive notes on players, or check gear without inspecting.]=] ] = [=[Décochez ceci pour désactiver toute communication entrante et sortante de Elitist Group.

Vous ne pourrez plus envoyer ou recevoir de notes sur les joueurs ou vérifier leur équipement sans les inspecter.]=]
L["Unholy"] = "Impie"
L["Unknown"] = "Inconnu"
L["URL"] = "URL"
L["User data not available yet."] = "Données d'utilisateur pas encore disponibles."
L["User data pruned"] = "Données de l'utilisateur effacées"
L["User %s is or went offline during syncing."] = "L'utilisateur est ou est passé hors ligne pendant la synchronisation."
L["Vault of Archavon"] = "Caveau d'Archavon"
L["View"] = "Voir"
L["View info on %s."] = "Voir les informations concernant %s."
L["View the group on ElitistArmory.com"] = "Voir le groupe sur ElitistArmory.com"
L["View the player on ElitistArmory.com"] = "Voir le joueur sur ElitistArmory.com"
L["Welcome! Type /elitistgroup help (or /eg help) to see a list of available slash commands."] = "Bienvenue ! Tapez /elitistgroup help (ou /eg help) pour voir une liste des commandes slash disponibles."
L["When automatically scanning your group, this is the number of inspects that will be saved so you can still inspect other people while the scan runs.|n|nThe more inspects you keep, the longer a scan will take."] = "Lors de l'analyse automatique de votre groupe, ceci représentera le nombre d'inspections qui seront mises de côté afin que vous puissiez toujours inspecter d'autres personnes pendant que l'analyse s'effectue.|n|nPlus vous mettez de côté d'inspections, plus une analyse sera longue."
L["When /eg summary is closed, the group inspect queue will always be processed.|n|nUnchecking this means the inspect queue is reset when /eg summary is closed."] = "Quand /eg summary est fermé, la file d'inspection du groupe continuera à être traitée.|n|nDécocher ceci signifie que la file d'inspection est réinitialisée quand /eg summary est fermé."
L["when hit"] = "lorsque vous êtes touché"
L[ [=[Whether enchants should be included in the report.

When set, it will show people with a percentage of bad enchants higher than the entered amount.]=] ] = [=[Intègre ou non les enchantements dans le rapport.

Quand définit, ceci vous montrera les personnes qui ont un pourcentage de mauvais enchantements supérieur à celui indiqué.]=]
L[ [=[Whether equipment should be included in the report.

When set, it will show people with a percentage of bad gear higher than the entered amount.]=] ] = [=[Intègre ou non l'équipement dans le rapport.

Quand définit, ceci vous montrera les personnes qui ont un pourcentage de mauvais équipement supérieur à celui indiqué.]=]
L["Whether item level should be included in the report, or only show average item levels below the selected value."] = "Intègre ou non le niveau d'objet dans le rapport, ou affiche uniquement les niveaux d'objet inférieurs à la valeur sélectionnée."
L["While the player data should be accurate, it is not guaranteed as the source is unverified."] = "Bien que les données de ce joueur peuvent être exactes, cela n'est pas garanti étant donnée que la source n'est pas fiable."
L["Yes"] = "Oui"
L["You are not inside chat channel #%d, can't send report."] = "Vous n'êtes pas dans le canal de discussion #%d, impossible d'envoyer le rapport."
L["You can choose which channels communication is accepted over. As long as communications are enabled, whisper is accepted. Communications are queued while in combat regardless."] = "Vous pouvez choisir quels canaux de communication sont acceptés. Tant que les communications sont activées, le canal des chuchotements est accepté. Dans tous les cas, les communications sont mises en attente pendant les combats."
L["You can edit or add a note on this player here."] = "Vous pouvez éditer ou ajouter une note concernant ce joueur ici."
L["You cannot request the database of everyone in your guild without being a guild!"] = "Vous ne pouvez pas demander la base de données de tous les membres de la guilde sans être dans une guilde !"
L["You cannot request the notes of everyone in your guild without being a guild!"] = "Vous ne pouvez pas demander les notes de tous les membres de la guilde sans être dans une guilde !"
L["You can only send a report once every 60 seconds."] = "Vous ne pouvez envoyer de rapport qu'une fois toutes les 60 secondes."
L["You did not set a channel to report to."] = "Vous n'avez pas définit de canal dans lequel rapporter."
L["You have not set a main yet."] = "Vous n'avez pas encore défini de personnage principal."
L["You have to add %s to your trusted list before you can use this."] = "Vous devez ajouter %s à votre liste de confiance avant de pouvoir utiliser ceci."
L["You have to enter a name for this to work."] = "Vous devez entrer un nom pour que ceci fonctionne."
L["You must be in a group to use this."] = "Vous devez être dans un groupe pour utiliser ceci."
L["You need to be in a guild to output to this channel."] = "Vous devez être dans une guilde pour envoyer dans ce canal."
L["You need to be in a party to output to this channel."] = "Vous devez être dans un groupe pour envoyer dans ce canal."
L["You need to be in a raid to output to this channel."] = "Vous devez être dans un raid pour envoyer dans ce canal."
L["You need to currently be in a group, or have been in a group to use the rating tool."] = "Vous devez être dans un groupe ou avoir été dans un groupe pour utiliser l'outil d'évaluation."
L["You need to enable database syncing in /eg config -> Addon communication to use this."] = "Vous devez activer la synchronisation de la base de données dans \"/eg config -> Communications de l'addon\" pour utiliser ceci."
L["Your main is currently: %s."] = "Votre personnage principal est actuellement : %s."
L[ [=[You wrote %s ago:
|cffffffff%s|r]=] ] = [=[Vous avez écrit il y a %s :
|cffffffff%s|r]=]

local ElitistGroup = select(2, ...)
ElitistGroup.L = setmetatable(L, {__index = ElitistGroup.L})
