if( GetLocale() ~= "zhTW" ) then return end
local L = {}
L["--"] = "--"
L["---"] = "--"
L["<1 minute old"] = "<1 分鐘前"
L["Active"] = "活動"
L["Add"] = "新增"
L["Add an user manually"] = "手動新增一個使用者"
L["Addon communication"] = "插件訊息"
L["Adds summary information to the main inspection window."] = "新增摘要資訊到主要觀察視窗。"
L["Adds tooltips when mousing over inspected items indicating the items type, and if the gems and enchants pass."] = "當滑鼠移過要觀察的物品時新增說明物品類型的提示，以及寶石跟附魔是否合格。"
L["Affliction"] = "痛苦系"
L["After completing a dungeon through the Looking For Dungeon system, automatically popup the /rate frame so you can set notes and rating on your group members."] = "在通過地城搜尋器完成一個副本後，自動彈出 /rate 視窗，這樣你可以為你的隊伍成員設定註解和評分。"
L["Alerts you in chat when you receive new notes or gear information from somebody."] = "當你接收到其他人的新註解或是裝備訊息時在聊天視窗警告你"
L["Alert when grouped with low rated players"] = "警報當編組到有低評分的玩家"
L["All"] = "全部"
L["Allow database syncing"] = "允許資料庫同步中"
L["Allow gear requests"] = "允許裝備要求"
L["Allows both you and other people on your trusted list to send and request your database of users."] = "在你信任名單中允許你和其他人發送和請求你的使用者資料庫。"
L["ALT + Left Click - Open report window for group"] = "ALT + 左鍵點擊 - 開啟通報群組視窗"
L["ALT + Right Click - Open rating window for party"] = "ALT+右鍵點擊 - 開啟隊伍評分視窗"
L["ALT + Right Click - Open rating window for raid"] = "ALT+右鍵點選 - 開啟團隊評分視窗"
L["Always bad"] = "總是不適合"
L["Always process group queue"] = "一直過程群組排隊"
L["Announce synced data"] = "發佈同步資料"
L["Any data from another server will not be saved, this includes notes! If you would like most of the data to be pruned but notes kept intact change basic pruning and leave this on."] = "任何來自其他伺服器的數據將不會被儲存，包括註解！如果你想要刪減大部分的數據但是保留完整的註解。"
L["Any data older than the set number will not be synced."] = "任何舊於數值的資料將不會同步。"
L["Arcane"] = "秘法"
L["Archavon the Stone Watcher"] = "『石之看守者』亞夏梵"
L["Archavon, Vault"] = "亞夏梵，穹殿"
L["Are you sure you want to reset ALL user data recorded, including notes?"] = "你確定想要重置全部使用者資料記錄，包括註解？"
L["armor by"] = "護甲"
L["armor for"] = "護甲的"
L["Arms"] = "武器"
L["Assassination"] = "刺殺"
L["Automatically"] = "自動地"
L["Automatically requests main experience (limited at once per an hour) when inspecting."] = "檢查時自動要求主經驗 (每小時限制一次)。"
L["Automatically requests notes on your group from other Elitist Group users. Only sends requests once per session, and you have to be in a guild."] = "從其他Elitist Group使用者自動在你的群組裡請求註解。每秒只發送一次請求，而且你必須在公會。"
L["Automatically trust all guild members, if you are in a guild."] = "自動信任全部公會會員，如果你是在一個公會。"
L["Automatically trusts all players on your friends list."] = "自動你的朋友列表裡信任全部玩家"
L["Auto request main experience"] = "自動要求本尊經驗"
L["Auto request notes"] = "自動請求註解"
L["Average"] = "平均"
L["[average ilvl]"] = "[平均物品等級]"
L["average item level below %d"] = "平均物品等級之下%d"
L["Average item level of the players equipment."] = "玩家平均物品裝備等級。"
L["Average rating %.2f of %d, rated %d times."] = "平均評分中 %.2f 之 %d，評分 %d 物品。"
L["[bad enchants]"] = "[不適合附魔]"
L["[bad equipment]"] = "[不適合裝備]"
L["[bad gems]"] = "[不適合寶石]"
L["Balance"] = "平衡"
L["Battleground channel"] = "戰場頻道"
L["Beast Mastery"] = "野獸控制"
L["Blood"] = "血魄"
L["c%-\"(.-)\""] = "c%-\"(.-)\""
L["Cannot find record of %s in your saved database."] = "在你已儲存資料庫找不到 %s 的記錄。"
L["Cannot find URL for this player, don't seem to have name, server or region data."] = "找不到此玩家的網址，似乎沒有名字，伺服器或地區的資料。 "
L["Cannot inspect %s yet, you have to wait %.1f seconds before you can inspect again."] = "無法檢查 %s, 但你必須等待 %.1f 秒前, 然後你可再次檢查。"
L["Caster (All)"] = "法系 (全部)"
L["Caster (Spirit)"] = "法系 (精神)"
L["|cff%02x%02x00%d|r avg, %d-man (%s)"] = "平均|cff%02x%02x00%d|r，%d-人(%s)"
L["[|cff%02x%02x00%d%%|r] Enchants"] = "[|cff%02x%02x00%d%%|r] 附魔"
L["[|cff%02x%02x00%d%%|r] Equipment (%s%d|r)"] = "[|cff%02x%02x00%d%%|r] 裝備 (%s%d|r) "
L["[|cff%02x%02x00%d%%|r] Gems"] = "[|cff%02x%02x00%d%%|r] 寶石"
L["[|cff%02x%02x00%d%%|r] [%s%d|r] Equipment"] = "[|cff%02x%02x00%d%%|r] [%s%d|r] 裝備"
L["|cfffed000Item Type:|r %s%s"] = "|cfffed000物品類型:|r %s%s"
L["[|cffff20200%|r] Enchants"] = "[|cffff20200%|r] 附魔"
L["[|cffff20200%|r] Gems"] = "[|cffff20200%|r] 寶石"
L["|cffff2020%d unspent |4point:points;|r"] = "|cffff2020%d 未用 |4提示:提示;|r"
L["|cffff2020%d unspent|r (Secondary)"] = "|cffff2020%d 未用|r (輔助)"
L["|cffff2020Warning!|r %s is in your group, you rated them %d"] = "|cffff2020警告!|r %s 在你的群組，你評分他們 %d"
L["|cffff2020Warning!|r %s is in your group, you rated them %d for: %s"] = "|cffff2020警告!|r %s 在你的群組，你評分他們 %d 之：%s"
L[ [=[
|cffffffffAND|r
]=] ] = "|cffffffff和|r"
L[ [=[
|cffffffffOR|r
]=] ] = "|cffffffff或|r"
L["|cffffffff%s|r %s, %s role."] = "|cffffffff%s|r %s, %s 角色。"
L[ [=[|cffffffff%s|r %s, %s role.

The player has not spent %d talent points.]=] ] = [=[|cffffffff%s|r %s，%s 角色。

此玩家沒花 %d 的天賦點數。]=]
L[ [=[|cffffffff%s|r %s, %s role.

The player put all of his talent points into one tree.]=] ] = [=[|cffffffff%s|r %s, %s 角色.

這玩家把他所有天賦點數點到一個天賦樹裡面。]=]
L["chance on melee and range"] = "近戰及遠程有一定機率"
L["chance on melee attack"] = "近戰攻擊有一定機率"
L["chance on melee or range"] = "近戰或遠程有一定機率"
L["Channel to report Elitist Group summary to."] = "頻道通報Elitist Group摘要。"
L["Classes"] = "職業"
L["Click to open and close the database viewer."] = "點擊開啟和關閉資料庫檢視器。"
L["Click to view detailed information."] = "點選檢視詳細的資訊"
L["Combat"] = "戰鬥"
L["Comment"] = "註解"
L["Comment..."] = "註釋..."
L["Completed %s! Type /rate to rate this group."] = "已完成%s！輸入 /rate 評分此群組。"
L["Could not calculate average item level, no data found."] = "無法計算平均物品等級，找無資料。"
L[ [=[Current filters are all players who have:

]=] ] = [=[目前擁有過濾器的所有玩家:
]=]
L["Custom list"] = "自訂列表"
L["<= %d"] = "<= %d"
L["> %d%%"] = "> %d%%"
L["%d |4day:days;"] = "%d |4天:天;"
L["%d |4day:days; old"] = "%d |4天:天; 前"
L["%d |4hour:hours;"] = "%d |4小時:小時;"
L["%d |4hour:hours; old"] = "%d |4小時:小時; 前"
L["%d |4minute:minutes;"] = "%d |4分鐘:分鐘;"
L["%d |4minute:minutes; old"] = "%d |4分鐘:分鐘; 前"
L["Database"] = "資料庫"
L["Data for this player is from a verified source and can be trusted."] = "此玩家的資料是從一個已證實的來源可以信任。 "
L[ [=[Data has been pruned to save database space.

Perhaps you want to change prune settings in /eg config?]=] ] = [=[數據已經精簡來保留數據庫空間。

或許你想要改變精簡設定用/eg config？]=]
L["Data is loading, please wait."] = "資料讀取中，請等待。"
L["%d average rating"] = "%d 平均評分"
L[">= %d%% bad enchants"] = ">= %d%% 不適合附魔"
L["> %d%% bad gear"] = "> %d%% 不適合裝備"
L[">= %d%% bad gems"] = ">= %d%% 不適合寶石"
L["deal damage"] = "造成傷害"
L["Delete"] = "刪除"
L["Demonology"] = "惡魔學識"
L["Destruction"] = "毀滅"
L["Discipline"] = "戒律"
L[" (%d-man)"] = "(%d-人)"
L[ [=[Do not abuse this!

Abuse will result in the feature being removed.]=] ] = [=[不要濫用這個!

濫用將造成未來被刪除。]=]
L["Do not require players who are below the given level."] = "不需要在低於特定等級的玩家。"
L["Don't include"] = "不包含"
L["Don't include enchants"] = "不包含附魔"
L["Don't include gear"] = "不包含裝備"
L["Don't include gems"] = "不包含寶石"
L["Don't include item level"] = "不包含物品等級"
L["%d%% or more bad enchants"] = "%d%% 或是更多不適合的附魔"
L["%d%% or more bad equipped items"] = "%d%% 或是更多不適合裝備的物品"
L["%d%% or more bad gems"] = "%d%% 或是更多不適合的寶石"
L["DPS (All)"] = "DPS (全部)"
L["DPS (Caster)"] = "DPS (法系)"
L["DPS, Caster"] = "DPS，法系"
L["DPS (Melee)"] = "DPS (近戰)"
L["DPS, Melee"] = "DPS，近戰"
L["DPS (Physical)"] = "DPS (物理)"
L["DPS (Ranged)"] = "DPS (遠程)"
L["DPS, Ranged"] = "DPS，遠戰"
L["Dungeons"] = "地城"
L["%d unspent |4point:points;"] = "%d 未用完|4點數:點數;"
L[" (%d unused |4socket:sockets;)"] = "(%d 未使用過 |4插槽:插槽;)"
L["Edit"] = "編輯"
L["/eg config - Opens the configuration"] = "/eg config - 開啟此設定"
L["/eg db [name] - Requests either everyones database or [name]s database if specified"] = "/eg db [名稱] - 請求無論任何人的資料庫或是如果有[名稱]的指定資料庫"
L["/eg gear <name> - Requests gear from another Elitist Group user without inspecting"] = "/eg gear <name> - 從另外 Elitist Group 使用者要求裝備差距不檢查"
L["/eg leader - Opens the specialized group manager/former UI"] = "/eg leader - 打開專用群管理/前者插件"
L["/eg <name> - When <name> is passed opens up the player viewer for that person, otherwise it opens it on yourself"] = "/eg <名稱> - 在<名稱>是合格開啟那位玩家的檢視器，否則你就要自己開啟"
L["/eg notes [name] - Requests all guild members notes on players, if [name] is passed requests notes FROM [name]"] = "/eg notes [名稱] - 在玩家中請求所有公會成員的註解，如果[名稱]是從[名稱]合格請求註解"
L["/eg rate - Opens the rating panel for your group"] = "/eg rate - 開啟你的群組評分面板"
L["/eg report - Opens the reporting UI for sending to chat summaries on your group"] = "/eg report - 設定通報訊息到你的群組頻道"
L["/eg send <name> - Sends your gear to another Elitist Group user"] = "/eg send <name> - 發送你的裝備差距至另外 Elitist Group 使用者"
L["/eg summary - Displays the summary page for your party or raid"] = "/eg summary - 顯示你的隊伍或團隊摘要頁面"
L["Elemental"] = "元素"
L["Elitist Group (%s): showing %d players, check out http://elitistarmory.com for more info. Format is, [name] (%s)"] = "Elitist Group (%s): 顯示 %d 的玩家, 檢查 http://elitistarmory.com 更多資訊。格式, [name] (%s)"
L["Emalon the Storm Watcher"] = "『風暴看守者』艾瑪隆"
L["Emalon, Vault"] = "艾瑪隆，穹殿"
L["Enable comms"] = "啟用通信"
L["Enabled channels"] = "啟用頻道"
L["Enchant"] = "附魔"
L["Enchant: |cffff2020[!]|r |cffffffffNone found|r"] = "附魔: |cffff2020[!]|r |cffffffff沒找到|r"
L["Enchant: |cffff2020[!]|r |cffffffff%s|r enchant"] = "附魔: |cffff2020[!]|r |cffffffff%s|r 附魔"
L["Enchant: |cffffffffCannot enchant|r"] = "附魔: |cffffffff不能附魔|r"
L["Enchant: |cffffffffPass|r"] = "附魔: |cffffffff合格|r"
L["Enchants"] = "附魔"
L["Enchants [|cff%02x%02x00%d%%|r]"] = "附魔 [|cff%02x%02x00%d%%|r]"
L["Enchants [|cffff20200%|r]"] = "附魔 [|cffff20200%|r]"
L["Enchants: |cffffffff%d bad|r"] = "附魔: |cffffffff%d 不適合|r"
L["Enchants: |cffffffffPass|r"] = "附魔: |cffffffff合格|r"
L["Enchants: |cffffffffThe player does not have any enchants|r"] = "附魔: |cffffffff此玩家沒有任何附魔|r"
L["Enhancement"] = "增強"
L["Equipment"] = "裝備"
L["Equipment: |cffffffff%d bad items found|r"] = "裝備: |cffffffff%d 找到不適合物品|r"
L["Equipment: |cffffffffPass|r"] = "裝備: |cffffffff合格|r"
L["Experience"] = "經驗"
L["Experienced"] = "經驗"
L["fear duration"] = "恐懼期間"
L["Feral"] = "野獸"
L["Fire"] = "火焰"
L["Frost"] = "冰霜"
L["Fury"] = "狂怒"
L["Gear"] = "裝備"
L["Gear received from %s."] = "裝備接收從%s。"
L["Gems"] = "寶石"
L["Gems [|cff%02x%02x00%d%%|r]"] = "寶石 [|cff%02x%02x00%d%%|r]"
L["Gems [|cffff20200%|r]"] = "寶石 [|cffff20200%|r]"
L["Gems: |cffff2020[!]|r |cffffffff%d bad|r%s"] = "寶石: |cffff2020[!]|r |cffffffff%d 不適合|r%s"
L["Gems: |cffffffff%d bad|r"] = "寶石: |cffffffff%d 不適合|r"
L["Gems: |cffffffffFailed to find any gems|r"] = "寶石: |cffffffff沒有找到任何寶石|r"
L["Gems: |cffffffffNo sockets|r"] = "寶石: |cffffffff未插寶石|r"
L["Gems: |cffffffffPass|r"] = "寶石: |cffffffff合格|r"
L["Gems/Enchant"] = "寶石/附魔"
L["General"] = "一般"
L["Great"] = "優秀"
L["guild"] = "公會"
L["Guild"] = "公會"
L["Guild channel"] = "公會頻道"
L["Hard"] = "困難"
L["harmful spell"] = "有害法術"
L["Healer"] = "治療"
L["Healer (All)"] = "治療 (全部)"
L["Healer/DPS"] = "治療/DPS"
L["Healing Priest/Druid"] = "治療的牧師/德魯伊"
L["Help"] = "說明"
L["helpful spell"] = "有益法術"
L["Heroic"] = "英雄"
L["Holy"] = "神聖"
L["How many days before removing all data on a player. This includes comments and ratings, even your own!"] = "移除幾天前玩家的所有資料，包含註解和評分，甚至是自己。"
L[ [=[How many days before talents/experience/equipment should be pruned, notes will be kept!

If the player has no notes or rating on them, all data is removed.]=] ] = [=[在天賦/經驗/裝備被信任前需要多少天，註解會保留!

如果玩家沒有註解或是評分在上面，所有資料已經被移除。]=]
L["How many inspects to save"] = "多少次檢查至儲存"
L["Icecrown Citadel"] = "冰冠城塞"
L["If you leave a rating on somebody of 2 or less, the next time you group with them you will get a warning in chat."] = "如果你留下2或是更少的某些人評分，下個期間你編輯他們在聊天頻道你會得到一個警告訊息。"
L["Ignore below level"] = "忽略在等級以下"
L["Ignore data older than (days)"] = "忽略資料舊於(天數)"
L["Inexperienced"] = "經驗不足"
L["Inspecting only in an instance"] = "只在副本檢查"
L["Inspection"] = "檢查"
L["Inspect queue empty"] = "觀察順序空的"
L["Instead of listing item link when viewing overall status, you'll instead see the name of the slot."] = "當檢視所有細節而不是列物品清單連結，你反而會看見插槽名稱。"
L["Integrate tooltips"] = "整合提示"
L["Integrate window"] = "整合視窗"
L["Item #%d not in cache"] = "物品 #%d 不在儲存器"
L["Item levels <= %d"] = "物品等級 <= %d"
L["Koralon the Flame Watcher"] = "『烈焰看守者』寇拉隆"
L["Koralon, Vault"] = "寇拉隆，穹殿"
L["Left Click - Open player/target information"] = "左鍵點擊 - 開啟玩家/目標資訊"
L["Loading"] = "讀取中"
L["Loading data"] = "正在讀取資料"
L["magical heals"] = "魔法癒合"
L["Main/alt experience"] = "本尊/分身經驗"
L["Mains experience on left, %s on right"] = "本尊經驗在左邊，%s 在右邊"
L["Make %s my main"] = "做 %s 我的本尊"
L["Malygos"] = "瑪里苟斯"
L["Marksmanship"] = "射擊"
L["Match all filters"] = "分配所有過濾器"
L[ [=[Match all item level, gear, enchant and gem filters to report.

If unchecked, only have to match one.]=] ] = [=[分配所有物品等級，裝備，附魔和寶石過濾器來通報。

如果未確認，只需要分配一個。]=]
L["Melee (All)"] = "近戰 (全部)"
L["melee and ranged"] = "近戰及遠程"
L["melee or range"] = "近戰或遠程"
L["n%-\"(.-)\""] = "n%-\"(.-)\""
L["Name"] = "名稱"
L["Naxxramas"] = "納克薩瑪斯"
L["Nearly-experienced"] = "幾乎經驗"
L["No"] = "否"
L[" (no belt buckle)"] = "(無腰帶扣環)"
L["Nobody in your group matched the entered filters."] = "在你的群組裡沒有人適合你輸入的過濾器。"
L["No channel selected"] = "沒有選擇頻道"
L["No comment"] = "沒有註解"
L["No data found for %s, and an inspection is pending. You'll have to wait a second and try again."] = "未找到 %s 的資料, 並且直到檢查時為止。你將等待秒鐘之後再試。"
L["No data found on group, you might need to wait a minute for it to load."] = "找無群組資料，你可能需要稍微等待載入資料。"
L["No enchants found"] = "沒附魔找到"
L["No enchants found."] = "找不到附魔。"
L["No filters are enabled, nothing to report based off of."] = "無過濾器啟用，沒有任何通報的基礎上發展。"
L["No filters setup, you need at least one to report."] = "無過濾器安裝，你需要至少一個來通報。"
L["No gems found."] = "沒找到寶石。"
L["No gems found. Possibly due to a data error, but most likely they do not have any."] = "寶石沒找到。可能由於資料錯誤，但更可能他們沒有。"
L["No item equipped"] = "沒裝備物品"
L["No notes found"] = "沒有找到註解"
L["No notes were found for this player."] = "無法找到此玩家的註解。"
L["No player found for unit %s."] = "找不到玩家單元%s。"
L["No rating data on this player found."] = "無法找到此玩家評分資料。"
L["Normal"] = "普通"
L["No secondary spec"] = "沒有第二天賦"
L["Notes (%d)"] = "註解(%d)"
L["Nothing is wrong with this players enchants!"] = "玩家的附魔沒有什麼問題！"
L["Nothing is wrong with this players equipment!"] = "玩家的裝備沒有什麼問題！"
L["Nothing is wrong with this players gems!"] = "玩家的寶石沒有什麼問題！"
L["Not rated"] = "沒有評分"
L["officer"] = "幹部"
L["Officer"] = "幹部"
L["Ok"] = "確定"
L["Onyxia's Lair"] = "奧妮克希亞的巢穴"
L["Other players have left a note on this person."] = "其他玩家在這人留下註解。"
L["party"] = "隊伍"
L["Party"] = "隊伍"
L["Party channel"] = "隊伍頻道"
L["periodic damage"] = "週期性傷害"
L["Physical (All)"] = "物理 (全部)"
L["Player info"] = "玩家訊息"
L["Play on alts all the time? Check out /eg config -> Main/alt experience to have your mains achievements carry over."] = "所有的時間都在玩分身? 檢查 /eg config -> 本尊/分身經驗讓你的本尊的成就繼續存在。"
L["Pops up the summary window when you first zone into an instance using the Looking for Dungeon system showing you info on your group."] = "當你使用地城搜尋器進入到一個副本區域開啟摘要視窗來顯示你在的群組訊息。"
L["Protection"] = "防護"
L["Prune all data (days)"] = "刪除全部資料(天數)"
L["Prune basic data (days)"] = "刪除基本資料(天數)"
L["Purified/Shiny Shard of the Flame are only good if the player also has the \"of the Scale\" trinket."] = "純淨龍鱗裂片/純淨烈焰裂片是好的除非玩家也有\"裂片\"飾品。"
L["PVP"] = "PVP"
L["PVP/Elemental Shaman"] = "PVP/元素系薩滿"
L["Queue: %d players left"] = "順序：%d 玩家離開"
L["raid"] = "團隊"
L["Raid"] = "團隊"
L["Raid channel"] = "團隊頻道"
L["Raids"] = "團隊"
L["ranged critical"] = "遠程致命"
L["Rated %d of %d"] = "已評分%d之%d"
L["Rating"] = "評分中"
L["Remove"] = "移除"
L["Report"] = "通報"
L["Report to channel %s"] = "通報到頻道%s"
L["Requested gear from %s, this might take a second."] = "要求從%s的裝備差距，這可能需要秒數。"
L["Requesting Elitist Group database from %s. Keep in mind this is hard throttled at once per hour."] = "要求從 %s 的 Elitist Group 資料庫. 請注意這個操作每小時強制最大次數為一次。"
L["Requesting Elitist Group databases from everyone in your guild, this could take a while. Keep in mind this is hard throttled at once per hour."] = "從你公會中所有人請求Elitist Group資料庫，這可能需要一點時間，請注意這個操作每小時強制最大次數為一次。"
L["Requesting Elitist Group notes from everyone in your guild, this could take a minute. Keep in mind this is hard throttled at onnce every 30 minutes."] = "從你公會裡的所有人請求Elitist Group註解，這將會花費一點時間，請注意這個操作每30分鐘強制最大次數為一次。"
L["Requesting Elitist Group notes from %s. Keep in mind this is hard throttled at once every 30 minutes."] = "請求從 %s 的 Elitist Group 註解，請注意這個操作每30分鐘強制最大次數為一次。"
L["Reset all user data."] = "重置全部使用者資料。"
L["Restoration"] = "恢復系"
L["Retribution"] = "懲戒"
L["Revitalizing meta requires a Solace of the Fallen/Defeated trinket for it to be a good meta gem for Restoration Shamans."] = "恢復變化依靠墮落撫慰/落敗撫慰飾品為恢復薩滿變成一個好的變換寶石。"
L["Right Click - Open summary for your party"] = "右鍵點擊 - 開啟你的隊伍摘要"
L["Right Click - Open summary for your raid"] = "右鍵點擊 - 開啟你的團隊摘要"
L["Role"] = "角色"
L["root duration"] = "基礎時間"
L["run speed"] = "跑速度"
L["s%-\"(.-)\""] = "s%-\"(.-)\""
L["Sartharion"] = "撒爾薩里安"
L["Save foreign server data"] = "儲存跨伺服器資料"
L["%s - |cffffffff%d|r missing |4gem:gems;"] = "%s - |cffffffff%d|r 缺少 |4寶石:寶石;"
L["%s - |cffffffff%s|r"] = "%s - |cffffffff%s|r"
L["%s - |cffffffff%s|r gem"] = "%s - |cffffffff%s|r 寶石"
L["%s - |cffffffff%s|r item"] = "%s - |cffffffff%s|r 物品"
L["%s - |cffffffff%s|r quality gem"] = "%s - |cffffffff%s|r 品質寶石"
L["%s - %d-man %s (%s)"] = "%s - %d-人 %s (%s)"
L["%s does not have any users to send you."] = "%s 沒有任何使用者發送給你。"
L["(%s%d|r) Gear [|cff%02x%02x00%d%%|r]"] = "(%s%d|r) 裝備 [|cff%02x%02x00%d%%|r]"
L["Search..."] = "搜尋..."
L["Secondary"] = "第二天賦"
L[ [=[Seen as %s - %s:
|cffffffff%s|r]=] ] = [=[發現為 %s - %s:
|cffffffff%s|r]=]
L["%s either disabled database syncing, or you are not on their trusted list."] = "%s 停用資料庫的同步，或是你不是在他們信任的列表。"
L["Select all"] = "選擇全部"
L["Semi-experienced"] = "一半經驗"
L["Sent your gear to %s! It will arrive in a few seconds"] = "發送你的裝備到%s！可能有幾秒鐘的延遲"
L["Set role as damage."] = "設定角色於傷害。"
L["Set role as healer."] = "設定角色於治療。"
L["Set role as tank."] = "設定角色於坦克。"
L["Shadow"] = "暗影"
L[ [=[Should you want finer control over who is on the trusted list, you can manually add players here.

Stored by faction/realm]=] ] = [=[如果你想要更精細的控制信任清單，你可以手動地在這裡新增玩家。

根據陣營/伺服器儲存]=]
L["Show rating after dungeon"] = "地城結束顯示評分"
L["Show slot names"] = "顯示插糟名稱"
L["Show summary on dungeon start"] = "在地城開始顯示摘要"
L["silence duration"] = "沈默期間"
L["Slash commands (/eg, /elitistgroup)"] = "斜線指令 (/eg, /elitistgroup) "
L["%s - Missing belt buckle or gem"] = "%s - 缺少腰帶扣環或寶石"
L["spell damage"] = "法術傷害"
L["%s, %s"] = "%s，%s"
L["%s - %s, level %s %s."] = "%s - %s，%s等級 %s。"
L["%s - %s, level %s, unknown class."] = "%s - %s, %s等級，未知職業"
L["%s, %s role."] = "%s，%s 角色。"
L[ [=[%s, %s role.

This player has not spent all of their talent points!]=] ] = [=[%s，%s 角色。

此玩家沒有花所有的天賦點數！]=]
L["%s: %s - %s, level %s %s"] = "%s: %s - %s，%s等級 %s"
L["%s: %s - %s, level %s, unknown class"] = "%s: %s - %s，%s等級，未知職業"
L["%s (Trusted)"] = "%s (信任)"
L["stun duration"] = "昏迷期間"
L["stun resistance"] = "打昏抵抗"
L["Subtlety"] = "敏銳"
L["Suggested dungeons"] = "建議地城"
L["Suitational (Caster)"] = "職位(法系)"
L["Suitational (Healer)"] = "職位(治療)"
L["%s - Unenchanted"] = "%s - 未附魔"
L["%s, unknown class"] = "%s，未知職業"
L["%s (Untrusted)"] = "%s (不信任)"
L["Survival"] = "生存"
L["T10 Dungeons"] = "T10 地城"
L["T7 Dungeons"] = "T7 地城"
L["T9 Dungeons"] = "T9 地城"
L["Talents unavailable"] = "天賦無效"
L["Tank"] = "坦克"
L["Tank/DPS"] = "坦克/DPS"
L["Tank/PVP"] = "坦克/PVP"
L["Tank/Ranged DPS"] = "坦克/遠程DPS"
L["Terrible"] = "極差"
L["The data you see should be accurate. However, it is not guaranteed as it is from an unverified source."] = "你看到的數據應該是精確的。無論如何，從未經證實的來源不敢保證。"
L["The player has not purchased dual specialization yet."] = "此玩家還沒買雙天賦。"
L["The Ruby Sanctum"] = "晶紅聖所"
L["Toravon the Ice Watcher"] = "『寒冰看守者』拓拉梵"
L["Trial of the Crusader"] = "十字軍試煉"
L["Trial of the Grand Crusader"] = "大十字軍試煉"
L["Trust friends"] = "信任朋友"
L["Trust guild members"] = "信任公會會員"
L["Trust list and addon communication options can be found in the menu to your left."] = "信任清單和插件訊息設定可以在你的選單中左邊被找到。"
L[ [=[Trust list is an easy way for you to see at a glance how much faith can be placed in data. It is also used for determining whether somebody can send or receive database and full note requests.
Both parties have to be on each others trust lists.]=] ] = [=[信任清單對你而言是一個很簡單的方法可以立刻看見有多少信任被放置在資料中。也被用來判定是否其他人可以發送或是接收資料庫和大量的註解請求。
雙方必須在各自的信任清單中。]=]
L["Trust management"] = "信任管理"
L["Ulduar"] = "奧杜亞"
L["Unchecking this disables other Elitist Group users from requesting your gear without inspecting."] = "不選此來禁止其他 Elitist Group 用戶不通過檢視直接請求你的裝備。"
L[ [=[Unchecking this will completely disable all communications in Elitist Group.

You will not be able to send or receive notes on players, or check gear without inspecting.]=] ] = [=[在Elitist Group沒有確認這項將會完全禁用所有訊息。

你將不能向其他玩家發送或請求註解，或沒有觀察就檢查裝備。]=]
L["Unholy"] = "穢邪"
L["Unknown"] = "未知"
L["URL"] = "網址"
L["User data not available yet."] = "使用者資料尚無效。"
L["User data pruned"] = "使用者資料減少"
L["User %s is or went offline during syncing."] = "使用者 %s 在同步時可能離線。"
L["Vault of Archavon"] = "亞夏梵穹殿"
L["View"] = "檢視"
L["View info on %s."] = "檢視資訊在%s。"
L["View the group on ElitistArmory.com"] = "檢視群組在 ElitistArmory.com"
L["View the player on ElitistArmory.com"] = "在ElitistArmory.com 查看此玩家資訊"
L["Welcome! Type /elitistgroup help (or /eg help) to see a list of available slash commands."] = "歡迎！指令 /elitistgroup help (或是 /eg help) 看到可用列表斜線指令。"
L["when hit"] = "當擊中"
L[ [=[Whether enchants should be included in the report.

When set, it will show people with a percentage of bad enchants higher than the entered amount.]=] ] = [=[不論附魔是否應該包含在通報中。

當你設定，就會顯示玩家不適合附魔百分比高於輸入的數字。]=]
L[ [=[Whether equipment should be included in the report.

When set, it will show people with a percentage of bad gear higher than the entered amount.]=] ] = [=[不論裝備是否應該包含在通報中。

當你設定，就會顯示玩家不適合裝備百分比高於輸入的數字。]=]
L["Whether item level should be included in the report, or only show average item levels below the selected value."] = "不論物品等級是否應該包含在通報中，或是只顯示平均物品等級在選定的數值下。"
L["While the player data should be accurate, it is not guaranteed as the source is unverified."] = "當此玩家資料應該是精準，無法確定來源是經過證實的。"
L["Yes"] = "是"
L["You are not inside chat channel #%d, can't send report."] = "你不再頻道#%d裡面，無法發送通報。"
L["You can choose which channels communication is accepted over. As long as communications are enabled, whisper is accepted. Communications are queued while in combat regardless."] = "你可以選擇被接受的頻道訊息。只要訊息啟用，密語被允許。當你在戰鬥中沒有注意訊息就會被排序。"
L["You can edit or add a note on this player here."] = "你可以在這裡編輯或新增此玩家的註解。"
L["You cannot request the database of everyone in your guild without being a guild!"] = "在你的公會中你不能在沒有公會的狀態下向任何人請求資料庫。"
L["You cannot request the notes of everyone in your guild without being a guild!"] = "在你的公會裡沒有一個公會成員你無法向每個人請求註解！"
L["You can only send a report once every 60 seconds."] = "你只可以在每60秒內通報一次。"
L["You did not set a channel to report to."] = "你無法設定頻道來通報。"
L["You have not set a main yet."] = "你還沒設定本尊。"
L["You have to add %s to your trusted list before you can use this."] = "在你可以使用這個以前你必須新增%s到你信用的名單中。"
L["You have to enter a name for this to work."] = "你必須為這項工作輸入一個名稱。"
L["You must be in a group to use this."] = "你必須在一個群組才可用。"
L["You need to be in a guild to output to this channel."] = "你必須在一個公會來輸出到這個頻道。"
L["You need to be in a party to output to this channel."] = "你必須在一個隊伍來輸出到這個頻道。"
L["You need to be in a raid to output to this channel."] = "你必須在一個團隊來輸出到這個頻道。"
L["You need to currently be in a group, or have been in a group to use the rating tool."] = "目前你需要一個群組，或已有一個群組來使用評分工具。"
L["You need to enable database syncing in /eg config -> Addon communication to use this."] = "你必須啟用資料庫同步用/eg config -> 插件訊息來使用。"
L["Your main is currently: %s."] = "你的本尊現在：%s。"
L[ [=[You wrote %s ago:
|cffffffff%s|r]=] ] = [=[你寫入 %s 前:\n|cffffffff%s|r
|cffffffff%s|r]=]

local ElitistGroup = select(2, ...)
ElitistGroup.L = setmetatable(L, {__index = ElitistGroup.L})
